### A Pluto.jl notebook ###
# v0.20.13

#> [frontmatter]
#> title = "Ray Tomography"
#> tags = ["raytheory"]
#> layout = "layout.jlhtml"
#> description = "This notebook focuses on the inverse formulation of 2-D first-arrival travel times."

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    #! format: off
    return quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
    #! format: on
end

# ╔═╡ dcaeb6a8-78d1-11ec-24fb-4509de0a7d7b
begin
    using Pluto
    using PlutoPlotly
    using PlutoTest
    using PlutoTeachingTools
    using LinearAlgebra
    using Distances
    using StatsBase
    using PlutoUI
	using Distributions
    using TikzPictures
    using SparseArrays
    using Colors, ColorSchemes, GLMNet
end

# ╔═╡ 07a56b99-964f-499d-913b-9c2aaeae6b51
using HDF5

# ╔═╡ 7e72f1fc-345a-4a2d-b03b-8a7549ef6efc
ChooseDisplayMode()

# ╔═╡ 35c21158-fc55-45f6-930d-7b82c2c0685d
TableOfContents(include_definitions=true)

# ╔═╡ d9d53d21-09ee-47cd-b661-8787de32f2c1
md"""
# Ray Tomography
Seismic tomography is a method used to create images of the Earth's subsurface using seismic waves generated by earthquakes or explosions. These waves, known as P-, S-, and surface waves, can be used to create tomographic models with varying resolutions, depending on factors such as the wavelength of the seismic waves, the distance of the wave source, and the source-receiver geometry. The process of creating these models is treated as an inverse problem, and this notebook specifically focuses on analyzing 2-D inversions of first-arrival travel times.

By interacting with this notebook, users will be able to:

* Visualize tomograms for various source-receiver configurations
* Understand the concept of ill-posedness and the need for regularization
* Learn about the principle of backpropagation
* And gain more insight into the field of seismic tomography

##### [Interactive Seismology Notebooks](https://pawbz.github.io/Interactive-Seismology.jl/)

Instructor: *Pawan Bharadwaj*,
Indian Institute of Science, Bengaluru, India
"""

# ╔═╡ f9089736-3744-4382-8bc0-68fc04b3cddb
md"""
## Forward Problem
In order to create an accurate image of the Earth's subsurface using seismic tomography, we need to first generate observed data. To do this, we will construct the forward operator $G$, which takes into account the model grid and the source-receiver setup. The forward problem is represented by the equation $G\times\,s$, where $s$ is the model (slowness) vector.
In this process, we will generate true seismic velocity and slowness arrays based on user input. These arrays will then be used to generate synthetic observations. 
"""

# ╔═╡ 5bbb5349-534a-48e2-8da5-08527784bc87
md"""
### Row Picture
The row picture of $G \times s$ illustrates the relationship between the slowness vector and the traveltime errors. It shows that the raypaths (rows of $G$) that have the strongest correlation with the slowness vector will have a higher traveltime error when compared to the others. This is because when a raypath passes through all the perturbed pixels of the medium, it will experience a greater delay, leading to a higher traveltime residual. In other words, the higher the correlation of a raypath with slowness vector, the more it is affected by the perturbations in the medium and hence higher traveltime residual.
"""

# ╔═╡ 7883ecc5-b01f-49d3-98c0-67676701e90e
md"### Column Picture
The column picture of $G \times s$ gives insight into the tradeoff between different pixels in the model grid. When two pixels are illuminated by a similar set of raypaths, they appear as dependent columns in the matrix $G$. As a result, these dependent columns can be linearly combined to produce no effect on the observed travel times. This means that changes in the slowness in these dependent pixels will not have any effect on the calculated traveltimes, and thus the solution to the inverse problem is not unique. It is important to keep in mind the tradeoff between these pixels while solving the inverse problem, and regularization may be needed to obtain a unique solution.
"

# ╔═╡ 792e9b54-3438-4338-913c-190565d38029
md"""## Backpropagation
Gradient is formed by backpropagation of traveltime residuals.
"""


# ╔═╡ 9a5bac04-d1d9-49f4-b7c4-b18bfdd436ef
md"""
### Column Picture
The column picture of $G^{\text{T}} \times \Delta d$ illustrates how the traveltime residuals are distributed across the model grid. It represents a weighted sum of the raypaths, where the weights are given by the traveltime residuals. This means that higher values in the model will be spread along the raypaths whose associated traveltimes do not match the observed traveltimes.
"""

# ╔═╡ 6680a1f4-0cc5-4dc8-a0a2-f5b5014c712a
md"""### Row Picture
The row picture of $G^{\text{T}} \times \Delta d$ represents the correlation between the model pixels and the data residuals. It shows that the model pixels whose ray distribution corresponds with the data residuals are given a larger weight. In other words, pixels that are intersected by high-residual rays are highlighted, or this means that the pixels in the model that are most responsible for the residuals in the data will be given more weight in the image.
"""

# ╔═╡ 924555b0-5ddc-4ee5-ad32-4696f9fb47e4
md"""
## Inverse Problem
Here, we shall simply use the Moore-Penrose pseudoinverse to map the observed travel times to slowness estimates. Note that the forward operator will now be generated again, based on the user input on spatial sampling of the seismic slowness, which is usually smaller compared to what we have used for generating the observed data above. 
"""

# ╔═╡ 4344de43-abfa-45c6-ab84-8578ba87f60f
λrange = logrange(1e-5, 1e5, length=100) |> collect

# ╔═╡ 1bc87b69-a59c-4074-b57d-011bf5e3df73
md"Finally, we will take the inverse of slowness and reshape it to produce the final 2-D seismic velocity model."

# ╔═╡ b6300fcc-8073-4487-80a2-8739123c1469
md"Check if the observations are satisfied by the estimated model."

# ╔═╡ 8fb45733-6b2b-428a-9536-fe6b6e2f2aa3
md"""
As a sanity check, we will now test the operator `G` by computing travel times in a homogeneous medium analytically. This will make sure that raytracing is done correctly.
"""

# ╔═╡ 1547ff9a-0fa8-4295-94dd-73bd3678129f
# get inverse operator using SVD (damped least squares)
# also returns the singular values for viz.
# commented for now
function get_inverse_operator(G)
    U, S, V = svd(G)
    Gi = V * Diagonal(inv.(S .+ 1e-1)) * U'
    return Gi, S
end

# ╔═╡ 848e19a7-73bc-40c4-98bb-310b9f9c8079
c = Dict(["Backpropagate the data residual" => :grad_slowness, "Estimate seismic velocity" => :cest])

# ╔═╡ df1f716a-f961-4f6b-821c-e1038f190449
md"## Uncertainity"

# ╔═╡ 27465f25-d6c7-4855-a20f-1142b8cd3e9f
md"[Scree plot](https://en.wikipedia.org/wiki/Scree_plot#:~:text=In%20multivariate%20statistics%2C%20a%20scree,principal%20component%20analysis%20(PCA).)"

# ╔═╡ 70e78f3d-a261-43b1-a590-966c7c96021c
md"Slider to choose the row of the Hessian matrix."

# ╔═╡ ae30bfd8-6b42-4aa7-90f2-e7303b359b94
md"""
We will now vis. rows of data and model resolution matrices.
"""

# ╔═╡ 010a12e2-1abc-4471-a81b-005c30578e63
md"## Appendix"

# ╔═╡ 6a0e653c-5a60-48d6-a3de-2c9409558b71
import PlutoUIExtra

# ╔═╡ 442255bc-4d49-4602-b0d4-a935871a9fe8
# define a for modelling and inversion

# ╔═╡ cf99206b-8a78-40de-bd0d-20bb37ec0b09
md"""
`get_medium` generates a medium with a background velocity of 2000 m/s,
and a circular perturbation. It outputs the velocity matrix and the corresponding slowness vector.
"""

# ╔═╡ 2bf78ef8-8fc5-4e0b-a7c0-f72757bae6f6
function get_medium(xgrid, zgrid, pert=nothing)
    nx = length(xgrid)
    nz = length(zgrid)
    ctrue = 2000.0 * ones(nz - 1, nx - 1)
    if !(pert === nothing) # check if perturbation is required
        # Generate random ellipticity and orientation
        a = pert.r * rand(Uniform(0.5, 2))
        b = pert.r * rand(Uniform(0.5, 2))
        theta = rand(Uniform(0, 2π))
        cos_theta = cos(theta)
        sin_theta = sin(theta)
        
        for iz in 1:nz-1, ix in 1:nx-1
            x = xgrid[ix] - pert.x
            z = zgrid[iz] - pert.z
            # Rotate coordinates
            x_rot = x * cos_theta + z * sin_theta
            z_rot = -x * sin_theta + z * cos_theta
            # Check if point is inside the ellipse
            if (x_rot / a)^2 + (z_rot / b)^2 < 1
                ctrue[iz, ix] += -100
            end
        end
    end
    strue = vec(inv.(ctrue))
    return ctrue, strue
end


# ╔═╡ 3d1cd3b5-66f5-44a8-805a-496e801be858
md"""
### Methods for straight-ray tracing
"""

# ╔═╡ 1040f2b8-3999-46fb-9e3d-c163264a4f8a
@warn "The straight-ray implementation in this notebook requires sources and receivers on the outer edge of the 2-D grid, i.e., arbitrary positions are not allowed."

# ╔═╡ f71dbf67-c6c2-444b-acf4-0569ee85bc6b
# careful before changing these; only place sources and receivers on the outer edge of the grid
function get_source_receivers_outer_edge(xgrid, zgrid, ns, nr)
    srcz = (ns == 1) ? [sample(zgrid)] : range(zgrid[2], stop=zgrid[end-1], length=ns)
    srcx = fill(xgrid[1], ns)
    recz = (nr == 1) ? [sample(zgrid)] : range(zgrid[2], stop=zgrid[end-1], length=nr)
    recx = fill(xgrid[end], nr)
    return srcz, srcx, recx, recz
end

# ╔═╡ 565af43c-8b85-4ab4-b72d-ac9560efd4fc
# find intersect b/w two segments
# returns nothing if 
# * segments are parallel 
# * segments do not intersect
# else returns 
# * the point of intersection (including C and D i.e., h==0 or h==1)
function find_intersect(A1, A2, B1, B2, C1, C2, D1, D2)
    # E = B - A
    # F = D - C = [D1-C1, D2-C2]
    # P = [A2-B2, B1-A1]
    dFP = (D1 - C1) * (A2 - B2) + (B1 - A1) * (D2 - C2)
    if (iszero(dFP)) # when parallel
        return nothing
    end
    h = ((A1 - C1) * (A2 - B2) + (A2 - C2) * (B1 - A1)) / dFP
    if (((h * (h - 1)) <= 0) | (h ≈ 0) | (h ≈ 1)) # h should be in (0, 1) or h==0 or h==1
        return [C1 + h * (D1 - C1), C2 + h * (D2 - C2)]
    else
        return nothing
    end
end

# ╔═╡ 3e2460ec-102a-4d3c-a4c5-5d6c6e2193ec
function find_length_in_cell(xmin, xmax, zmin, zmax, A1, A2, B1, B2)
    P1 = find_intersect(A1, A2, B1, B2, xmin, zmin, xmin, zmax)
    P2 = find_intersect(A1, A2, B1, B2, xmin, zmin, xmax, zmin)
    P3 = find_intersect(A1, A2, B1, B2, xmin, zmax, xmax, zmax)
    P4 = find_intersect(A1, A2, B1, B2, xmax, zmin, xmax, zmax)

    P = filter(x -> !(x === nothing), [P1, P2, P3, P4])
    P = unique(P)
    if (length(P) >= 2)
        # remove sides that will be otherwise counted twice by adjacent cells
        if (([xmin, zmax] ∈ P) & ([xmax, zmax] ∈ P))
            return 0
        elseif (([xmax, zmin] ∈ P) & ([xmax, zmax] ∈ P))
            return 0
        else
            return maximum(broadcast(x -> sqrt(sum(abs2.(x))), diff(P)))
        end
    else
        return 0
    end
end


# ╔═╡ 82d3a20f-ea2b-47e6-96df-45fa568da9f8
function get_forw_operator(xgrid, zgrid, srcx, srcz, recx, recz)
    nx = length(xgrid)
    nz = length(zgrid)
    ns = length(srcx)
    nr = length(recx)
    G = zeros(ns * nr, (nx - 1) * (nz - 1))
    for is in 1:ns, ir in 1:nr, iz in 1:nz-1, ix in 1:nx-1
        G[ir+(is-1)*nr, iz+(ix-1)*(nz-1)] = find_length_in_cell(xgrid[ix], xgrid[ix+1], zgrid[iz], zgrid[iz+1], srcx[is], srcz[is], recx[ir], recz[ir])
    end
    return G
end

# ╔═╡ 4daad9cb-5651-4757-a390-27bbbfa5d4c9

"""
Constructs a sparse matrix for horizontal differencing operator for an image of size (rows, cols).
"""
function horizontal_differencing_operator(rows, cols)
    num_pixels = rows * cols
    data = Float64[]
    row_indices = Int[]
    col_indices = Int[]

    for i in 1:rows, j in 1:cols-1
        pixel = (i - 1) * cols + j
        next_pixel = pixel + 1
        push!(data, -1.0)  # Difference from current pixel
        push!(data, 1.0)   # Difference to the next pixel
        append!(row_indices, [pixel, pixel])
        append!(col_indices, [pixel, next_pixel])
    end

    return sparse(row_indices, col_indices, data, num_pixels, num_pixels)
end

# ╔═╡ b4800358-212d-4efc-af6e-8bbdd53609e6
"""
Constructs a sparse matrix for vertical differencing operator for an image of size (rows, cols).
"""
function vertical_differencing_operator(rows, cols)
    num_pixels = rows * cols
    data = Float64[]
    row_indices = Int[]
    col_indices = Int[]

    for i in 1:rows-1, j in 1:cols
        pixel = (i - 1) * cols + j
        next_pixel = pixel + cols
        push!(data, -1.0)  # Difference from current pixel
        push!(data, 1.0)   # Difference to the next pixel
        append!(row_indices, [pixel, pixel])
        append!(col_indices, [pixel, next_pixel])
    end

    return sparse(row_indices, col_indices, data, num_pixels, num_pixels)
end

# ╔═╡ 4dd5df1f-f0bc-49ec-a533-4498ed17d223
md"""
### UI
"""

# ╔═╡ 208932c4-a57b-487d-9d3b-f165b4a4a4ed
function perturbation_input(xgrid, zgrid)
    nx = length(xgrid)
    nz = length(zgrid)
    return PlutoUI.combine() do Child
        p = [
            md"""
x= $(Child("x", Slider(xgrid, default=xgrid[div(nx,2)], show_value=true)))
			""",
			md"""
                     and z= $(Child("z", Slider(zgrid, default=zgrid[div(nz,2)], show_value=true)))
                     """,
        ]
        r = [
            md"""
            $(Child("r", Slider(range(10, stop=500, length=10), default=330, show_value=true)))
            """,]

        md"""### Medium Parameters
Circular perturbation at $(p) with scale ∈ [10, 500] m
	$(r)
 """
    end
end

# ╔═╡ 7e6ae5d6-ff89-45f5-914a-c58d3e185041
function resolution_input()
    return PlutoUI.combine() do Child
        d = [
            md"""
Resolution (m) of true $(Child("ds", Slider(range(10,stop=200), default=25, show_value=true)))
			""",
			md"""
            and inverted $(Child("ds_inv", Slider(range(10,stop=200), default=150, show_value=true))) media
            """,
        ]

        md"$(d)"
    end
end

# ╔═╡ bd08b641-e332-4b9b-9a44-2aea39d80b6c
PlutoUIExtra.Sidebar(
	md"#### Inversion Parameters",
	(@bind res confirm(resolution_input())),
	md"---",
	md"Choose the regularization parameter", (@bind λ Slider(λrange, show_value=true)),
	
	location="lower left"
)

# ╔═╡ da873791-517d-4ac3-80f8-ceae5808be24
begin
    xgrid = range(-1000, stop=1000, length=floor(Int, 2000 / res.ds))
    zgrid = range(-1000, stop=1000, length=floor(Int, 2000 / res.ds))
end;

# ╔═╡ 81f6f055-fd51-455a-9dae-bc8a03b0d94f
PlutoUIExtra.Sidebar(
	(@bind pert confirm(perturbation_input(xgrid, zgrid))),
	md"---",
	(@bind regenerate_medium CounterButton("Regenerate Medium")), location="upper left"
)

# ╔═╡ 092331da-31a4-403d-b0cb-6e7705c6d81b
begin
	regenerate_medium
	ctrue, strue = get_medium(xgrid, zgrid, pert);
end

# ╔═╡ 322d1562-2197-4131-bd17-93aed063e55c
begin
    xgrid_inv = range(-1000, stop=1000, length=floor(Int, 2000 / res.ds_inv))
    zgrid_inv = range(-1000, stop=1000, length=floor(Int, 2000 / res.ds_inv))
end;

# ╔═╡ fe682b63-2a06-4c32-8dc0-2f99ba48a873
@bind irowm Slider(1:(length(xgrid_inv)-1)*(length(zgrid_inv)-1), show_value=true, default=div(length(xgrid_inv) * length(zgrid_inv), 4))

# ╔═╡ 272428e7-f865-4d9e-9df1-9fb45dec6a96
Dv = vertical_differencing_operator(length(zgrid_inv) - 1, length(xgrid_inv) - 1,)

# ╔═╡ 0ac7a1d4-f9c4-4e9a-a1fd-ff7629022fad
Dh = horizontal_differencing_operator(length(zgrid_inv) - 1, length(xgrid_inv) - 1,)

# ╔═╡ 59c0e9a2-ab43-45b8-83a8-e0e865b1895d
λ3 = inv(tr(Dh' * Dh))

# ╔═╡ 6702fde2-8847-407b-9d69-8e099374d6ce
function acq_input()
    return PlutoUI.combine() do Child
        d = [
            md"""
            Choose number of sources $(Child("ns", Slider(2:2:50, show_value=true, default=25)))
            """,
			md"""
			and receivers $(Child("nr", Slider(2:2:50, show_value=true, default=25)))
			"""
        ]

        md"""
  ### Acquisition Setup
  $(d)
  """
    end
end

# ╔═╡ 3b3342fd-e1f9-4bb0-ac0e-580b2ec2af2b
PlutoUIExtra.Sidebar(
	(@bind acq confirm(acq_input())), location="center left"
)

# ╔═╡ aa9782b5-88be-43a2-b1e1-d68f289a8fec
srcz, srcx, recx, recz = get_source_receivers_outer_edge(xgrid, zgrid, acq.ns, acq.nr);

# ╔═╡ 7df1cd87-40fa-45c1-9d85-1d491c414a18
Gtrue = get_forw_operator(xgrid, zgrid, srcx, srcz, recx, recz);

# ╔═╡ 3d201819-788b-4d90-b3a6-5483fc16ca81
dobs = Gtrue * strue;

# ╔═╡ dce75e41-274b-4e6a-8949-5caaeef7238a
G = get_forw_operator(xgrid_inv, zgrid_inv, srcx, srcz, recx, recz);

# ╔═╡ ad441089-505f-4da2-a345-548e8c4dd7d2
plot(heatmap(z=G), Layout(xaxis_title="model vector index", yaxis_autorange="reversed", yaxis_title="data vector index", width=450, title="Forward Operator"))

# ╔═╡ 2713503d-165f-47f9-8ece-4cd5ddc0bb21
λ1 = inv(tr(G' * G))

# ╔═╡ a60daaa3-d5da-4ac5-b40b-65bbbffdae55
H = spdiagm(ones(size(G, 2)));

# ╔═╡ 464f5a71-d820-4300-b062-e2eb9491f612
λ2 = inv(tr(H' * H))

# ╔═╡ 774ebdcf-3d88-47b8-aa66-f59822b18321
Gi = pinv(G); # compute Moore-Penrose pseudoinverse

# ╔═╡ 80910abe-97df-4283-bc18-d8c8e876174e
sprior = fill(inv(2000.), size(G, 2));

# ╔═╡ fc4be0cb-5531-4432-a265-30f0cc27494d
function get_tikhonov_solution(dobs)
	return inv(λ1 * G' * G + λ2 * λ * H' * H) * (
    λ1 * G' * dobs + λ2 * λ * H' * sprior)
end

# ╔═╡ e4d99869-844e-4c1b-a64c-9cbf1eabab99
sest1 = get_tikhonov_solution(dobs)

# ╔═╡ 68b24556-4731-4b8f-b8a6-7aa7ffa38a92
cest1 = reshape((inv.(sest1)), length(zgrid_inv) - 1, length(xgrid_inv) - 1);

# ╔═╡ 11ffa65f-6c38-48bd-b22b-07c238596473
function get_first_difference_regularized_solution(dobs)
	return inv(λ1 * G' * G + λ3 * λ * Dh' * Dh + λ3 * λ * Dv' * Dv) * (
    λ1 * G' * dobs)
end

# ╔═╡ 0a336d04-b2c5-45d6-b2a4-7f03666cb597
sest2 = get_first_difference_regularized_solution(dobs)

# ╔═╡ 9dfe9cd4-9baa-4808-9b7a-d01c62ee6d40
cest2 = reshape((inv.(sest2)), length(zgrid_inv) - 1, length(xgrid_inv) - 1);

# ╔═╡ a26fd943-dd6c-4e42-b6b0-5c9a17f31b19
plot([scatter(y=dobs, name="observed"), scatter(y=G * sest1, name="predicted")], Layout(title="Data Residual (Observed Vs. Predicted Traveltimes)", xaxis_title="# raypath", yaxis_title="traveltime"))

# ╔═╡ ffb59613-e16b-4d38-9c36-c778f92842e0
plot([scatter(y=dobs, name="observed"), scatter(y=G * sest2, name="predicted")], Layout(title="Data Residual (Observed Vs. Predicted Traveltimes)", xaxis_title="# raypath", yaxis_title="traveltime"))

# ╔═╡ acc8d4d0-a332-478f-8630-b22a10e7063b
function plot_G_scree()
    s = svd(G)
    plot(s.S, Layout(title="Singular values of G"))
end

# ╔═╡ aa36d8d7-a7d4-4aa4-b0ee-b07d36cc453b
plot_G_scree()

# ╔═╡ 3c7cddb2-72c6-45d1-a902-f66cb67d2835
plot(heatmap(z=transpose(G) * G), Layout(yaxis_autorange="reversed", title="the Hessian matrix", xaxis_title="model index", yaxis_title="model index", width=450))

# ╔═╡ f408a310-fce3-4876-819e-3457037bd48f
plot(heatmap(x=xgrid_inv, y=zgrid_inv, z=reshape((transpose(G)*G)[irowm, :], length(zgrid_inv) - 1, length(xgrid_inv) - 1)), Layout(yaxis_autorange="reversed", title="row of the Hessian matrix", width=450))

# ╔═╡ 5bdd9d83-3911-4ab5-aefb-5ead429ac5a5
plot(heatmap(x=xgrid_inv, y=zgrid_inv, z=reshape((Gi*G)[irowm, :], length(zgrid_inv) - 1, length(xgrid_inv) - 1)),
    Layout(yaxis_autorange="reversed", title="Row of Model Resolution Matrix", width=450))

# ╔═╡ 58867c8d-af21-48e9-ab0c-4472711e8eb0
begin
    tt_analytic = vec([(sqrt(sum(abs2.([srcx[is] - recx[ir], srcz[is] - recz[ir]])))) * inv(2000) for ir in 1:acq.nr, is in 1:acq.ns])
    tt_G = G * inv.(fill(2000, (length(zgrid_inv) - 1) * (length(xgrid_inv) - 1)))
    @test tt_analytic ≈ tt_G
end

# ╔═╡ 0bf44317-45cf-4899-8b1b-dfa1fe018db4
data_residual = tt_G - dobs;

# ╔═╡ 461859c0-5f94-469c-a054-4553045bac17
grad_slowness = reshape(G' * data_residual, length(zgrid_inv) - 1, length(xgrid_inv) - 1);

# ╔═╡ 1807eb3a-ce0b-46fe-8c70-fa4af3d9ebad
@bind irowd Slider(1:acq.nr*acq.ns, show_value=true)

# ╔═╡ a3bf8549-fff8-4423-8a87-a81cb21f9eb1
plot((G*Gi)[irowd, :], Layout(title="Row of data resolution matrix", xaxis_title="raypath index"))

# ╔═╡ b338591d-cc11-4e9e-827e-7fcee5b2d38b
md"### Plots"

# ╔═╡ b1350eb1-059e-4f83-a539-2e2befc3dabb
function plot_models()

    fig = Plot(Layout(yaxis_autorange="reversed", height=600, width=650, title=attr(font_size=12,), font=attr(
            size=10), yaxis=attr(scaleanchor="x"), Subplots(shared_xaxes=true, shared_yaxes=true, horizontal_spacing=0.3, rows=2, cols=2, subplot_titles=["True Seismic Velocity" "Gradient" "Tikhonov Regularization" "First-Order Difference Regularization"])))
    add_trace!(fig, heatmap(
            x=xgrid,
            y=zgrid,
            z=reshape(ctrue, length(zgrid) - 1, length(xgrid) - 1), colorscale="jet", colorbar=attr(x=0.35, y=0.75, len=0.25)), row=1, col=1)
    add_trace!(fig, heatmap(
            x=xgrid_inv,
            y=zgrid_inv,
            z=(grad_slowness), colorscale="jet", colorbar=attr(x=1, y=0.75, len=0.25)), row=1, col=2)

    add_trace!(fig, heatmap(
            x=xgrid_inv,
            y=zgrid_inv,
            z=(cest1), colorscale="jet", colorbar=attr(x=0.35, y=0.25, len=0.25), zmin=minimum(ctrue), zmax=maximum(ctrue)), row=2, col=1)
    add_trace!(fig, heatmap(
            x=xgrid_inv,
            y=zgrid_inv,
            z=(cest2), colorscale="jet", colorbar=attr(x=1, y=0.25, len=0.25), zmin=minimum(ctrue), zmax=maximum(ctrue)), row=2, col=2)

    return PlutoPlotly.plot(fig)

end

# ╔═╡ 842ec98f-505a-4873-9c64-725e2f92cbb9
plot_models()

# ╔═╡ 4114f8f4-51a5-4af6-b8b7-e17480d942e3
# Normalize residuals to [0,1]
norm_residuals = (data_residual .- minimum(data_residual)) ./ (maximum(data_residual) - minimum(data_residual))

# ╔═╡ e8e733ee-586d-4ef6-a8ad-8c793cc8e3e9
# Map to seismic colormap (blue → red)
data_residual_colors = get.(Ref(reverse(colorschemes[:seismic])), norm_residuals)

# ╔═╡ 44eddeed-1763-4c04-b213-b7469983286d
# data_residual_colors = get.(Ref(colorschemes[:seismic]), (data_residual .- minimum(data_residual)) ./ maximum(data_residual));

# ╔═╡ 1161cc82-6b2d-42e0-99fe-2dfb1a2d00b6
ray_setup = broadcast(reshape(1:acq.nr, acq.nr, 1), reshape(1:acq.ns, 1, acq.ns)) do ir, is
    scatter(x=[srcx[is], recx[ir]], y=[srcz[is], recz[ir]], marker=attr(symbol=["asterisk", "triangle-down"], size=[10, 10], line=attr(color="black"), color=data_residual_colors[ir+(is-1)*acq.nr]), opacity=0.15, mode="lines+markers",)
end;

# ╔═╡ d7dd7859-9489-4bfc-bc77-edec76fe96f2
function plot_ray_setup()
    return plot(vec(ray_setup), Layout(yaxis_autorange="reversed", font=attr(
            size=10), showlegend=false, width=450, title="Ray Geometry<br>(red ray paths have higher data residuals)", yaxis_tickvals=zgrid_inv, xaxis_tickvals=xgrid_inv, xaxis=attr(title="x", ticks="outside", tickwidth=1, tickcolor="black", ticklen=10, gridcolor="gray"), yaxis=attr(title="z", scaleanchor="x", ticks="outside", tickwidth=1, tickcolor="black", ticklen=10, gridcolor="gray"), xaxis_zeroline=false, yaxis_zeroline=false,))
end


# ╔═╡ 4509e5b8-8d54-47e1-9ba7-b4929fd2d2fc
plot_ray_setup()

# ╔═╡ 1499710e-1316-4113-b551-83d0e01151ab
# ╠═╡ disabled = true
#=╠═╡
h5open("ray_tomography_assignment_Jan2025.h5", "w") do file
    write(file, "G", G) 
	 write(file, "d", dobs)
	write(file, "xgrid_inv", collect(xgrid_inv))
	write(file, "zgrid_inv", collect(zgrid_inv)) 
	write(file, "srcx", srcx)
	write(file, "srcz", collect(srcz))
	write(file, "recx", collect(recx))
	write(file, "recz", collect(recz)) 
end
  ╠═╡ =#

# ╔═╡ ce416101-f2e1-4b67-a166-b099325c3be2
md"### Tikz"

# ╔═╡ 6428269b-4821-48a3-b46b-38a06bf9aa1a
tikz_default_options = raw"""
  background rectangle/.style={fill=white}, show background rectangle,
  """

# ╔═╡ d974f740-2c3e-4225-bed8-f444bccde910
tikz_preamble = raw"""
  \usepackage{tikz}
  \usepackage{tikz}
  \usetikzlibrary{fit, matrix, shapes.geometric}
  \tikzset{% use tikzset, not tikzstyle
      cell/.style={
          rectangle, rounded corners=5pt, draw,
      }
  }
  \tikzset{% use tikzset, not tikzstyle
      cellv/.style={
          rectangle, rounded corners=5pt, draw, rotate=90,
      }
  }
  \usepackage{xifthen}
  \usetikzlibrary{hobby}
  \usepackage{pgfplots}
  \usepackage{fontawesome}
  \usepackage{bm,amsfonts,amsmath}
  \usetikzlibrary{backgrounds,pgfplots.groupplots,snakes}
  \usepgfplotslibrary{patchplots}
  \pgfplotsset{try min ticks=2}
  \usepackage{pgfplotstable} 
  \usetikzlibrary{plotmarks,positioning,spy}
  \usetikzlibrary{shapes.geometric, arrows, fadings}
  \usepgfplotslibrary{groupplots, polar}
  \usepackage[space]{grffile}

  \usetikzlibrary{%
              decorations.pathreplacing,%
                  decorations.pathmorphing%
                  }
                  \usetikzlibrary{positioning,fit,backgrounds}



  \usetikzlibrary{shapes,arrows}
  \usetikzlibrary{decorations.markings}
  \usetikzlibrary{patterns}
  \usetikzlibrary{plotmarks}
  \usetikzlibrary{fit}
  \usetikzlibrary{intersections}
  \usepgfplotslibrary{fillbetween}

    \pgfplotsset{
                axis line style={black!10},
                    every axis label/.append style ={black!10},
                    every axis title/.append style ={black!10},
                        every tick label/.append style={black!10}  
                          }

  % need for pgfplots
  \newcommand{\axisz}{0cm}
  \newcommand{\axisx}{0cm}

  \usetikzlibrary{positioning}
  \usetikzlibrary{shapes.geometric}
  \usetikzlibrary{backgrounds}
  """

# ╔═╡ d06052d3-07c3-43b6-909d-b31b06097fd3
# t1, t2, t3, tv are texts
# s1 and s2 are labels with sizes
plot_tikzrow(t1, t2, tn, tv; s1="", s2="") = TikzPicture(L"""
   \matrix[
              matrix of nodes, nodes in empty cells,
              minimum width=4cm,
              column sep=4pt,
              row sep=10pt,
              text height=2ex, text depth=.25ex,
              minimum height=4ex,
  left delimiter={[},
          right delimiter={]},
              ] (m) {
              |[cell]| %$(t1) \\
  |[cell]| %$(t2) \\
  |[cell]| $\cdots$ \\
   			|[cell]| %$(tn) \\
          } ; 
  \matrix[
   right=of m,
              matrix of nodes, nodes in empty cells,
              %minimum width=4cm,
              column sep=4pt,
              row sep=10pt,
              text height=2ex, text depth=.25ex,
              %minimum height=4cm,
  left delimiter={[},
          right delimiter={]},
  ] (m2) {
           |[rotate=90]| %$(tv) \\
          } ;

  \node [below of=m2, node distance = 5em,] () {%$(s2)}; 
  \node [below of=m, node distance = 6em,] () {%$(s1)}; 

  """, options=tikz_default_options, preamble=tikz_preamble, width="12cm")

# ╔═╡ 8037f78d-8938-42fc-98a2-210b442c00f0
plot_tikzrow("raypath 1", "raypath 2", "raypath K", "slowness vector", s1="K×N", s2="N×1")

# ╔═╡ cad88757-7a23-4c99-84fe-219d9337a1f7
plot_tikzrow("model pixel 1", "model pixel 2", "model pixel N", "data residual", s1="N×K", s2="K×1")

# ╔═╡ 0d000f59-ecb2-4fc9-9f21-c60eac17b3bf
# t1, t2, t3, tv are texts
# s1 and s2 are labels with sizes
plot_tikzcol(t1, t2, tn, tv; s1="", s2="") = TikzPicture(L"""
   \matrix[
              matrix of nodes, nodes in empty cells,
              minimum width=4cm, minimum height=1cm,
              column sep=4pt,
              row sep=10pt,
  %            text height=2ex, 
  rotate=90,
  text depth=.25ex,
  left delimiter={[},
          right delimiter={]},
              ] (m) {
              |[cellv]| %$(t1) & |[cellv]| %$(t2) & |[cellv]| $\cdots$ & |[cellv]| %$(tn) \\ 
          } ;
  \matrix[
   right=of m,
              matrix of nodes, nodes in empty cells,
              %minimum width=4cm,
              column sep=4pt,
              row sep=10pt,
              text height=2ex, text depth=.25ex,
              %minimum height=4cm,
  left delimiter={[},
          right delimiter={]},
  ] (m2) {
           |[rotate=90]| %$(tv) \\
          } ;
  \node [below of= m2,node distance = 5em,] () {%$(s2)}; 
  \node [below of= m, node distance = 7em,] () {%$(s1)};

  """, options=tikz_default_options, preamble=tikz_preamble, width="12cm")

# ╔═╡ 5dd62dd3-fc67-4043-9579-aea1b1a922a9
plot_tikzcol("model pixel 1", "model pixel 2", "model pixel N", "slowness vector", s1="K×N", s2="N×1")

# ╔═╡ 68c959c7-b8e9-4992-b4ce-a793d1a34d20
plot_tikzcol("raypath 1", "raypath 2", "raypath K", "data residual", s1="N×K", s2="K×1")

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoPlotly = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
PlutoTest = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PlutoUIExtra = "a011ac08-54e6-4ec3-ad1c-4165f16ac4ce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
ColorSchemes = "~3.24.0"
Colors = "~0.12.10"
Distances = "~0.10.11"
Distributions = "~0.25.115"
GLMNet = "~0.7.2"
HDF5 = "~0.17.2"
Pluto = "~0.20.17"
PlutoPlotly = "~0.4.4"
PlutoTeachingTools = "~0.2.14"
PlutoTest = "~0.2.2"
PlutoUI = "~0.7.55"
PlutoUIExtra = "~0.1.8"
StatsBase = "~0.34.2"
TikzPictures = "~3.5.0"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.6"
manifest_format = "2.0"
project_hash = "de9d1a4b42ceb298009f2250bcf0d168dd315c37"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "6e1d2a35f2f90a4bc7c2ed98079b2ba09c35b83a"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.3.2"

[[deps.Accessors]]
deps = ["CompositionsBase", "ConstructionBase", "Dates", "InverseFunctions", "MacroTools"]
git-tree-sha1 = "3b86719127f50670efe356bc11073d84b4ed7a5d"
uuid = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
version = "0.1.42"

    [deps.Accessors.extensions]
    AxisKeysExt = "AxisKeys"
    IntervalSetsExt = "IntervalSets"
    LinearAlgebraExt = "LinearAlgebra"
    StaticArraysExt = "StaticArrays"
    StructArraysExt = "StructArrays"
    TestExt = "Test"
    UnitfulExt = "Unitful"

    [deps.Accessors.weakdeps]
    AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
    IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
    LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
    StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
    StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.AliasTables]]
deps = ["PtrArrays", "Random"]
git-tree-sha1 = "9876e1e164b144ca45e9e3198d0b689cadfed9ff"
uuid = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
version = "1.1.3"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.2"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

[[deps.BaseDirs]]
git-tree-sha1 = "bca794632b8a9bbe159d56bf9e31c422671b35e0"
uuid = "18cc8868-cbac-4acf-b575-c8ff214dc66f"
version = "1.3.2"

[[deps.BitFlags]]
git-tree-sha1 = "0691e34b3bb8be9307330f88d1a3c3f25466c24d"
uuid = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
version = "0.1.9"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1b96ea4a01afe0ea4090c5c8039690672dd13f2e"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.9+0"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "CompilerSupportLibraries_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "2ac646d71d0d24b44f3f8c84da8c9f4d70fb67df"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.18.4+0"

[[deps.CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
git-tree-sha1 = "5ac098a7c8660e217ffac31dc2af0964a8c3182a"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "2.0.0"

[[deps.CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "962834c22b66e32aa10f7611c08c8ca4e20749a9"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.8"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "ColorVectorSpace", "Colors", "FixedPointNumbers", "PrecompileTools", "Random"]
git-tree-sha1 = "67c1f244b991cad9b0aa4b7540fb758c2488b129"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.24.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "b10d0b65641d57b8b4d5e234446582de5047050d"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.5"

[[deps.ColorVectorSpace]]
deps = ["ColorTypes", "FixedPointNumbers", "LinearAlgebra", "Requires", "Statistics", "TensorCore"]
git-tree-sha1 = "a1f44953f2382ebb937d60dafbe2deea4bd23249"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.10.0"
weakdeps = ["SpecialFunctions"]

    [deps.ColorVectorSpace.extensions]
    SpecialFunctionsExt = "SpecialFunctions"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "362a287c3aa50601b0bc359053d5c2468f0e7ce0"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.11"

[[deps.Compat]]
deps = ["TOML", "UUIDs"]
git-tree-sha1 = "0037835448781bb46feb39866934e243886d756a"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "4.18.0"
weakdeps = ["Dates", "LinearAlgebra"]

    [deps.Compat.extensions]
    CompatLinearAlgebraExt = "LinearAlgebra"

[[deps.Compiler]]
git-tree-sha1 = "382d79bfe72a406294faca39ef0c3cef6e6ce1f1"
uuid = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
version = "0.1.1"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "1.1.1+0"

[[deps.CompositionsBase]]
git-tree-sha1 = "802bb88cd69dfd1509f6670416bd4434015693ad"
uuid = "a33af91c-f02d-484b-be07-31d278c5ca2b"
version = "0.1.2"
weakdeps = ["InverseFunctions"]

    [deps.CompositionsBase.extensions]
    CompositionsBaseInverseFunctionsExt = "InverseFunctions"

[[deps.ConcurrentUtilities]]
deps = ["Serialization", "Sockets"]
git-tree-sha1 = "d9d26935a0bcffc87d2613ce14c527c99fc543fd"
uuid = "f0e56b4a-5159-44fe-b623-3e5288b988bb"
version = "2.5.0"

[[deps.Configurations]]
deps = ["ExproniconLite", "OrderedCollections", "TOML"]
git-tree-sha1 = "4358750bb58a3caefd5f37a4a0c5bfdbbf075252"
uuid = "5218b696-f38b-4ac9-8b61-a12ec717816d"
version = "0.17.6"

[[deps.ConstructionBase]]
git-tree-sha1 = "b4b092499347b18a015186eae3042f72267106cb"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.6.0"

    [deps.ConstructionBase.extensions]
    ConstructionBaseIntervalSetsExt = "IntervalSets"
    ConstructionBaseLinearAlgebraExt = "LinearAlgebra"
    ConstructionBaseStaticArraysExt = "StaticArrays"

    [deps.ConstructionBase.weakdeps]
    IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
    LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
    StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[[deps.Crayons]]
git-tree-sha1 = "249fe38abf76d48563e2f4556bebd215aa317e15"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.1.1"

[[deps.DataAPI]]
git-tree-sha1 = "abe83f3a2f1b857aac70ef8b269080af17764bbe"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.16.0"

[[deps.DataFrames]]
deps = ["Compat", "DataAPI", "DataStructures", "Future", "InlineStrings", "InvertedIndices", "IteratorInterfaceExtensions", "LinearAlgebra", "Markdown", "Missings", "PooledArrays", "PrecompileTools", "PrettyTables", "Printf", "Random", "Reexport", "SentinelArrays", "SortingAlgorithms", "Statistics", "TableTraits", "Tables", "Unicode"]
git-tree-sha1 = "a37ac0840a1196cd00317b57e39d6586bf0fd6f6"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "1.7.1"

[[deps.DataPipes]]
git-tree-sha1 = "29077a8d5c093f4e0988e92c0d76f56c4c581900"
uuid = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
version = "0.3.18"

[[deps.DataStructures]]
deps = ["OrderedCollections"]
git-tree-sha1 = "6c72198e6a101cccdd4c9731d3985e904ba26037"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.19.1"

[[deps.DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
git-tree-sha1 = "9e2f36d3c96a820c678f2f1f1782582fcf685bae"
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"
version = "1.9.1"

[[deps.Distances]]
deps = ["LinearAlgebra", "Statistics", "StatsAPI"]
git-tree-sha1 = "c7e3a542b999843086e2f29dac96a618c105be1d"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.10.12"

    [deps.Distances.extensions]
    DistancesChainRulesCoreExt = "ChainRulesCore"
    DistancesSparseArraysExt = "SparseArrays"

    [deps.Distances.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"
version = "1.11.0"

[[deps.Distributions]]
deps = ["AliasTables", "FillArrays", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SpecialFunctions", "Statistics", "StatsAPI", "StatsBase", "StatsFuns"]
git-tree-sha1 = "3e6d038b77f22791b8e3472b7c633acea1ecac06"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.25.120"

    [deps.Distributions.extensions]
    DistributionsChainRulesCoreExt = "ChainRulesCore"
    DistributionsDensityInterfaceExt = "DensityInterface"
    DistributionsTestExt = "Test"

    [deps.Distributions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.DocStringExtensions]]
git-tree-sha1 = "7442a5dfe1ebb773c29cc2962a8980f47221d76c"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.9.5"

[[deps.Downloads]]
deps = ["ArgTools", "FileWatching", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
version = "1.6.0"

[[deps.ExceptionUnwrapping]]
deps = ["Test"]
git-tree-sha1 = "d36f682e590a83d63d1c7dbd287573764682d12a"
uuid = "460bff9d-24e4-43bc-9d9f-a8973cb893f4"
version = "0.1.11"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "7bb1361afdb33c7f2b085aa49ea8fe1b0fb14e58"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.7.1+0"

[[deps.ExpressionExplorer]]
git-tree-sha1 = "4a8c0a9eebf807ac42f0f6de758e60a20be25ffb"
uuid = "21656369-7473-754a-2065-74616d696c43"
version = "1.1.3"

[[deps.ExproniconLite]]
git-tree-sha1 = "c13f0b150373771b0fdc1713c97860f8df12e6c2"
uuid = "55351af7-c7e9-48d6-89ff-24e801d99491"
version = "0.10.14"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
version = "1.11.0"

[[deps.FillArrays]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "6a70198746448456524cb442b8af316927ff3e1a"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "1.13.0"
weakdeps = ["PDMats", "SparseArrays", "Statistics"]

    [deps.FillArrays.extensions]
    FillArraysPDMatsExt = "PDMats"
    FillArraysSparseArraysExt = "SparseArrays"
    FillArraysStatisticsExt = "Statistics"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "05882d6995ae5c12bb5f36dd2ed3f61c98cbb172"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.5"

[[deps.FlexiMaps]]
deps = ["Accessors", "DataPipes", "InverseFunctions"]
git-tree-sha1 = "88fb6ab75454c21be1d75a0a430a0ed95f0d3f1e"
uuid = "6394faf6-06db-4fa8-b750-35ccc60383f7"
version = "0.1.28"

    [deps.FlexiMaps.extensions]
    AxisKeysExt = "AxisKeys"
    DictionariesExt = "Dictionaries"
    IntervalSetsExt = "IntervalSets"
    StructArraysExt = "StructArrays"
    UnitfulExt = "Unitful"

    [deps.FlexiMaps.weakdeps]
    AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
    Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
    IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
    StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Zlib_jll"]
git-tree-sha1 = "f85dac9a96a01087df6e3a749840015a0ca3817d"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.17.1+0"

[[deps.Format]]
git-tree-sha1 = "9c68794ef81b08086aeb32eeaf33531668d5f5fc"
uuid = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
version = "1.3.7"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Zlib_jll"]
git-tree-sha1 = "2c5512e11c791d1baed2049c5652441b28fc6a31"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.13.4+0"

[[deps.Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"
version = "1.11.0"

[[deps.GLMNet]]
deps = ["DataFrames", "Distributed", "Distributions", "Printf", "Random", "SparseArrays", "StatsBase", "glmnet_jll"]
git-tree-sha1 = "b873c384d3490304c18224b1d5554cdebaafb60b"
uuid = "8d5ece8b-de18-5317-b113-243142960cc6"
version = "0.7.4"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE2_jll", "Zlib_jll"]
git-tree-sha1 = "b0036b392358c80d2d2124746c2bf3d48d457938"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.82.4+0"

[[deps.GracefulPkg]]
deps = ["Compat", "Pkg", "TOML"]
git-tree-sha1 = "698050b04f3cc0906d0817329d6e96484bf238eb"
uuid = "828d9ff0-206c-6161-646e-6576656f7244"
version = "2.3.0"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "8a6dbda1fd736d60cc477d99f2e7a042acfa46e8"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.15+0"

[[deps.HDF5]]
deps = ["Compat", "HDF5_jll", "Libdl", "MPIPreferences", "Mmap", "Preferences", "Printf", "Random", "Requires", "UUIDs"]
git-tree-sha1 = "e856eef26cf5bf2b0f95f8f4fc37553c72c8641c"
uuid = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
version = "0.17.2"

    [deps.HDF5.extensions]
    MPIExt = "MPI"

    [deps.HDF5.weakdeps]
    MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[[deps.HDF5_jll]]
deps = ["Artifacts", "JLLWrappers", "LibCURL_jll", "Libdl", "OpenSSL_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "4cc2bb72df6ff40b055295fdef6d92955f9dede8"
uuid = "0234f1f7-429e-5d53-9886-15a909be8d59"
version = "1.12.2+2"

[[deps.HTTP]]
deps = ["Base64", "CodecZlib", "ConcurrentUtilities", "Dates", "ExceptionUnwrapping", "Logging", "LoggingExtras", "MbedTLS", "NetworkOptions", "OpenSSL", "PrecompileTools", "Random", "SimpleBufferStream", "Sockets", "URIs", "UUIDs"]
git-tree-sha1 = "ed5e9c58612c4e081aecdb6e1a479e18462e041e"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "1.10.17"

[[deps.HarfBuzz_ICU_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "HarfBuzz_jll", "ICU_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "6ccbc4fdf65c8197738c2d68cc55b74b19c97ac2"
uuid = "655565e8-fb53-5cb3-b0cd-aec1ca0647ea"
version = "2.8.1+0"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.HypergeometricFunctions]]
deps = ["LinearAlgebra", "OpenLibm_jll", "SpecialFunctions"]
git-tree-sha1 = "68c173f4f449de5b438ee67ed0c9c748dc31a2ec"
uuid = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
version = "0.3.28"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "179267cfa5e712760cd43dcae385d7ea90cc25a4"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.5"

[[deps.HypertextLiteral]]
deps = ["Tricks"]
git-tree-sha1 = "7134810b1afce04bbc1045ca1985fbe81ce17653"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.5"

[[deps.ICU_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "20b6765a3016e1fca0c9c93c80d50061b94218b7"
uuid = "a51ab1cf-af8e-5615-a023-bc2c838bba6b"
version = "69.1.0+0"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "b6d6bfdd7ce25b0f9b2f6b3dd56b2673a66c8770"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.5"

[[deps.InlineStrings]]
git-tree-sha1 = "8f3d257792a522b4601c24a577954b0a8cd7334d"
uuid = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
version = "1.4.5"

    [deps.InlineStrings.extensions]
    ArrowTypesExt = "ArrowTypes"
    ParsersExt = "Parsers"

    [deps.InlineStrings.weakdeps]
    ArrowTypes = "31f734f8-188a-4ce0-8406-c8a06bd891cd"
    Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

[[deps.IntervalSets]]
git-tree-sha1 = "5fbb102dcb8b1a858111ae81d56682376130517d"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.7.11"

    [deps.IntervalSets.extensions]
    IntervalSetsRandomExt = "Random"
    IntervalSetsRecipesBaseExt = "RecipesBase"
    IntervalSetsStatisticsExt = "Statistics"

    [deps.IntervalSets.weakdeps]
    Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
    RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
    Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[deps.InverseFunctions]]
git-tree-sha1 = "a779299d77cd080bf77b97535acecd73e1c5e5cb"
uuid = "3587e190-3f89-42d0-90ee-14403ec27112"
version = "0.1.17"
weakdeps = ["Dates", "Test"]

    [deps.InverseFunctions.extensions]
    InverseFunctionsDatesExt = "Dates"
    InverseFunctionsTestExt = "Test"

[[deps.InvertedIndices]]
git-tree-sha1 = "6da3c4316095de0f5ee2ebd875df8721e7e0bdbe"
uuid = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
version = "1.3.1"

[[deps.IrrationalConstants]]
git-tree-sha1 = "e2222959fbc6c19554dc15174c81bf7bf3aa691c"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.2.4"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[deps.JLLWrappers]]
deps = ["Artifacts", "Preferences"]
git-tree-sha1 = "0533e564aae234aff59ab625543145446d8b6ec2"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.7.1"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "31e996f0a15c7b280ba9f76636b3ff9e2ae58c9a"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.4"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "4255f0032eafd6451d707a51d5f0248b8a165e4d"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "3.1.3+0"

[[deps.JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
git-tree-sha1 = "d8337622fe53c05d16f031df24daf0270e53bc64"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.10.5"

[[deps.LERC_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "bf36f528eec6634efc60d7ec062008f171071434"
uuid = "88015f11-f218-50d7-93a8-a6af411a945d"
version = "3.0.0+1"

[[deps.LLVMOpenMP_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "eb62a3deb62fc6d8822c0c4bef73e4412419c5d8"
uuid = "1d63c593-3942-5779-bab2-d838dc0a180e"
version = "18.1.8+0"

[[deps.LRUCache]]
git-tree-sha1 = "5519b95a490ff5fe629c4a7aa3b3dfc9160498b3"
uuid = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
version = "1.6.2"
weakdeps = ["Serialization"]

    [deps.LRUCache.extensions]
    SerializationExt = ["Serialization"]

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1c602b1127f4751facb671441ca72715cc95938a"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.3+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "dda21b8cbd6a6c40d9d02a73230f9d70fed6918c"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.4.0"

[[deps.Latexify]]
deps = ["Format", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "OrderedCollections", "Requires"]
git-tree-sha1 = "cd10d2cc78d34c0e2a3a36420ab607b611debfbb"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.16.7"

    [deps.Latexify.extensions]
    DataFramesExt = "DataFrames"
    SparseArraysExt = "SparseArrays"
    SymEngineExt = "SymEngine"

    [deps.Latexify.weakdeps]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[[deps.LazilyInitializedFields]]
git-tree-sha1 = "0f2da712350b020bc3957f269c9caad516383ee0"
uuid = "0e77f7df-68c5-4e49-93ce-4cd80f5598bf"
version = "1.3.0"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.6.4"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "8.6.0+0"

[[deps.LibGit2]]
deps = ["Base64", "LibGit2_jll", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"
version = "1.11.0"

[[deps.LibGit2_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll"]
uuid = "e37daf67-58a4-590a-8e99-b0245dd2ffc5"
version = "1.7.2+0"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.11.0+1"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "27ecae93dd25ee0909666e6835051dd684cc035e"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+2"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "be484f5c92fad0bd8acfef35fe017900b0b73809"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.18.0+0"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "706dfd3c0dd56ca090e86884db6eda70fa7dd4af"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.41.1+0"

[[deps.Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "LERC_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "3eb79b0ca5764d4799c06699573fd8f533259713"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.4.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "d3c8af829abaeba27181db4acb485b18d15d89c6"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.41.1+0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "OpenBLAS_jll", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
version = "1.11.0"

[[deps.LittleCMS_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg"]
git-tree-sha1 = "110897e7db2d6836be22c18bffd9422218ee6284"
uuid = "d3a379c0-f9a3-5b72-a4c0-6bf4d2e8af0f"
version = "2.12.0+0"

[[deps.LogExpFunctions]]
deps = ["DocStringExtensions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "13ca9e2586b89836fd20cccf56e57e2b9ae7f38f"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.29"

    [deps.LogExpFunctions.extensions]
    LogExpFunctionsChainRulesCoreExt = "ChainRulesCore"
    LogExpFunctionsChangesOfVariablesExt = "ChangesOfVariables"
    LogExpFunctionsInverseFunctionsExt = "InverseFunctions"

    [deps.LogExpFunctions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
    InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

[[deps.LoggingExtras]]
deps = ["Dates", "Logging"]
git-tree-sha1 = "f02b56007b064fbfddb4c9cd60161b6dd0f40df3"
uuid = "e6f89c97-d47a-5376-807f-9c37f3926c36"
version = "1.1.0"

[[deps.LoweredCodeUtils]]
deps = ["CodeTracking", "Compiler", "JuliaInterpreter"]
git-tree-sha1 = "73b98709ad811a6f81d84e105f4f695c229385ba"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
version = "3.4.3"

[[deps.MIMEs]]
git-tree-sha1 = "c64d943587f7187e751162b3b84445bbbd79f691"
uuid = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
version = "1.1.0"

[[deps.MPIPreferences]]
deps = ["Libdl", "Preferences"]
git-tree-sha1 = "c105fe467859e7f6e9a852cb15cb4301126fac07"
uuid = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
version = "0.1.11"

[[deps.MacroTools]]
git-tree-sha1 = "1e0228a030642014fe5cfe68c2c0a818f9e3f522"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.16"

[[deps.Malt]]
deps = ["Distributed", "Logging", "RelocatableFolders", "Serialization", "Sockets"]
git-tree-sha1 = "636abf4fb184be05888dacc0b636fe0911d6d746"
uuid = "36869731-bdee-424d-aa32-cab38c994e3b"
version = "1.2.0"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "MozillaCACerts_jll", "NetworkOptions", "Random", "Sockets"]
git-tree-sha1 = "c067a280ddc25f196b5e7df3877c6b226d390aaf"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.1.9"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.28.6+0"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "ec4f7fbeab05d7747bdf98eb74d130a2a2ed298d"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.2.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
version = "1.11.0"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2023.12.12"

[[deps.MsgPack]]
deps = ["Serialization"]
git-tree-sha1 = "f5db02ae992c260e4826fe78c942954b48e1d9c2"
uuid = "99f44e22-a591-53d1-9472-aa23ef4bd671"
version = "1.2.1"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.2.0"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.27+1"

[[deps.OpenJpeg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libtiff_jll", "LittleCMS_jll", "Pkg", "libpng_jll"]
git-tree-sha1 = "76374b6e7f632c130e78100b166e5a48464256f8"
uuid = "643b3616-a352-519d-856d-80112ee9badc"
version = "2.4.0+0"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"
version = "0.8.5+0"

[[deps.OpenSSL]]
deps = ["BitFlags", "Dates", "MozillaCACerts_jll", "OpenSSL_jll", "Sockets"]
git-tree-sha1 = "f1a7e086c677df53e064e0fdd2c9d0b0833e3f6e"
uuid = "4d8831e6-92b7-49fb-bdf8-b643e874388c"
version = "1.5.0"

[[deps.OpenSSL_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "ad31332567b189f508a3ea8957a2640b1147ab00"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.23+1"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1346c9208249809840c91b26703912dff463d335"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.6+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "05868e21324cede2207c6f0f466b4bfef6d5e7ee"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.8.1"

[[deps.PCRE2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "efcefdf7-47ab-520b-bdef-62a2eaa19f15"
version = "10.42.0+1"

[[deps.PDMats]]
deps = ["LinearAlgebra", "SparseArrays", "SuiteSparse"]
git-tree-sha1 = "f07c06228a1c670ae4c87d1276b92c7c597fdda0"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.11.35"

[[deps.Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "34c0e9ad262e5f7fc75b10a9952ca7692cfc5fbe"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.3"

[[deps.Parsers]]
deps = ["Dates", "PrecompileTools", "UUIDs"]
git-tree-sha1 = "7d2f8f21da5db6a806faf7b9b292296da42b2810"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.8.3"

[[deps.Pixman_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "LLVMOpenMP_jll", "Libdl"]
git-tree-sha1 = "db76b1ecd5e9715f3d043cec13b2ec93ce015d53"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.44.2+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "Random", "SHA", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.11.0"
weakdeps = ["REPL"]

    [deps.Pkg.extensions]
    REPLExt = "REPL"

[[deps.PlotlyBase]]
deps = ["ColorSchemes", "Colors", "Dates", "DelimitedFiles", "DocStringExtensions", "JSON", "LaTeXStrings", "Logging", "Parameters", "Pkg", "REPL", "Requires", "Statistics", "UUIDs"]
git-tree-sha1 = "28278bb0053da0fd73537be94afd1682cc5a0a83"
uuid = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
version = "0.8.21"

    [deps.PlotlyBase.extensions]
    DataFramesExt = "DataFrames"
    DistributionsExt = "Distributions"
    IJuliaExt = "IJulia"
    JSON3Ext = "JSON3"

    [deps.PlotlyBase.weakdeps]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
    IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
    JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[[deps.Pluto]]
deps = ["Base64", "Configurations", "Dates", "Downloads", "ExpressionExplorer", "FileWatching", "GracefulPkg", "HTTP", "HypertextLiteral", "InteractiveUtils", "LRUCache", "Logging", "LoggingExtras", "MIMEs", "Malt", "Markdown", "MsgPack", "Pkg", "PlutoDependencyExplorer", "PrecompileSignatures", "PrecompileTools", "REPL", "RegistryInstances", "RelocatableFolders", "Scratch", "Sockets", "TOML", "Tables", "URIs", "UUIDs"]
git-tree-sha1 = "7cddd8a094d2eedf43f21be40d9090f4a5217255"
uuid = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
version = "0.20.17"

[[deps.PlutoDependencyExplorer]]
deps = ["ExpressionExplorer", "InteractiveUtils", "Markdown"]
git-tree-sha1 = "c3e5073a977b1c58b2d55c1ec187c3737e64e6af"
uuid = "72656b73-756c-7461-726b-72656b6b696b"
version = "1.2.2"

[[deps.PlutoHooks]]
deps = ["InteractiveUtils", "Markdown", "UUIDs"]
git-tree-sha1 = "072cdf20c9b0507fdd977d7d246d90030609674b"
uuid = "0ff47ea0-7a50-410d-8455-4348d5de0774"
version = "0.0.5"

[[deps.PlutoLinks]]
deps = ["FileWatching", "InteractiveUtils", "Markdown", "PlutoHooks", "Revise", "UUIDs"]
git-tree-sha1 = "8f5fa7056e6dcfb23ac5211de38e6c03f6367794"
uuid = "0ff47ea0-7a50-410d-8455-4348d5de0420"
version = "0.1.6"

[[deps.PlutoPlotly]]
deps = ["AbstractPlutoDingetjes", "BaseDirs", "Colors", "Dates", "Downloads", "HypertextLiteral", "InteractiveUtils", "LaTeXStrings", "Markdown", "Pkg", "PlotlyBase", "Reexport", "TOML"]
git-tree-sha1 = "1ae939782a5ce9a004484eab5416411c7190d3ce"
uuid = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
version = "0.4.6"

    [deps.PlutoPlotly.extensions]
    PlotlyKaleidoExt = "PlotlyKaleido"
    UnitfulExt = "Unitful"

    [deps.PlutoPlotly.weakdeps]
    PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.PlutoTeachingTools]]
deps = ["Downloads", "HypertextLiteral", "LaTeXStrings", "Latexify", "Markdown", "PlutoLinks", "PlutoUI", "Random"]
git-tree-sha1 = "5d9ab1a4faf25a62bb9d07ef0003396ac258ef1c"
uuid = "661c6b06-c737-4d37-b85c-46df65de6f69"
version = "0.2.15"

[[deps.PlutoTest]]
deps = ["HypertextLiteral", "InteractiveUtils", "Markdown", "Test"]
git-tree-sha1 = "17aa9b81106e661cffa1c4c36c17ee1c50a86eda"
uuid = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"
version = "0.2.2"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "Downloads", "FixedPointNumbers", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "MIMEs", "Markdown", "Random", "Reexport", "URIs", "UUIDs"]
git-tree-sha1 = "8329a3a4f75e178c11c1ce2342778bcbbbfa7e3c"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.71"

[[deps.PlutoUIExtra]]
deps = ["AbstractPlutoDingetjes", "ConstructionBase", "FlexiMaps", "HypertextLiteral", "InteractiveUtils", "IntervalSets", "Markdown", "PlutoUI", "Random", "Reexport"]
git-tree-sha1 = "b4ff5d24e2dc8fbf319cd44f9f81b5356e27bafb"
uuid = "a011ac08-54e6-4ec3-ad1c-4165f16ac4ce"
version = "0.1.8"

[[deps.PooledArrays]]
deps = ["DataAPI", "Future"]
git-tree-sha1 = "36d8b4b899628fb92c2749eb488d884a926614d3"
uuid = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
version = "1.4.3"

[[deps.Poppler_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "Glib_jll", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "OpenJpeg_jll", "Pkg", "libpng_jll"]
git-tree-sha1 = "02148a0cb2532f22c0589ceb75c110e168fb3d1f"
uuid = "9c32591e-4766-534b-9725-b71a8799265b"
version = "21.9.0+0"

[[deps.PrecompileSignatures]]
git-tree-sha1 = "18ef344185f25ee9d51d80e179f8dad33dc48eb1"
uuid = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
version = "3.0.3"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "5aa36f7049a63a1528fe8f7c3f2113413ffd4e1f"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.2.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "0f27480397253da18fe2c12a4ba4eb9eb208bf3d"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.5.0"

[[deps.PrettyTables]]
deps = ["Crayons", "LaTeXStrings", "Markdown", "PrecompileTools", "Printf", "Reexport", "StringManipulation", "Tables"]
git-tree-sha1 = "1101cd475833706e4d0e7b122218257178f48f34"
uuid = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
version = "2.4.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.PtrArrays]]
git-tree-sha1 = "1d36ef11a9aaf1e8b74dacc6a731dd1de8fd493d"
uuid = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"
version = "1.3.0"

[[deps.QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "9da16da70037ba9d701192e27befedefb91ec284"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.11.2"

    [deps.QuadGK.extensions]
    QuadGKEnzymeExt = "Enzyme"

    [deps.QuadGK.weakdeps]
    Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "StyledStrings", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.RegistryInstances]]
deps = ["LazilyInitializedFields", "Pkg", "TOML", "Tar"]
git-tree-sha1 = "ffd19052caf598b8653b99404058fce14828be51"
uuid = "2792f1a3-b283-48e8-9a74-f99dce5104f3"
version = "0.1.0"

[[deps.RelocatableFolders]]
deps = ["SHA", "Scratch"]
git-tree-sha1 = "ffdaf70d81cf6ff22c2b6e733c900c3321cab864"
uuid = "05181044-ff0b-4ac5-8273-598c1e38db00"
version = "1.0.1"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "62389eeff14780bfe55195b7204c0d8738436d64"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.1"

[[deps.Revise]]
deps = ["CodeTracking", "FileWatching", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "REPL", "Requires", "UUIDs", "Unicode"]
git-tree-sha1 = "d852eba0cc08181083a58d5eb9dccaec3129cb03"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "3.9.0"
weakdeps = ["Distributed"]

    [deps.Revise.extensions]
    DistributedExt = "Distributed"

[[deps.Rmath]]
deps = ["Random", "Rmath_jll"]
git-tree-sha1 = "852bd0f55565a9e973fcfee83a84413270224dc4"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.8.0"

[[deps.Rmath_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "58cdd8fb2201a6267e1db87ff148dd6c1dbd8ad8"
uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f"
version = "0.5.1+0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "9b81b8393e50b7d4e6d0a9f14e192294d3b7c109"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.3.0"

[[deps.SentinelArrays]]
deps = ["Dates", "Random"]
git-tree-sha1 = "712fb0231ee6f9120e005ccd56297abbc053e7e0"
uuid = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
version = "1.4.8"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
version = "1.11.0"

[[deps.SimpleBufferStream]]
git-tree-sha1 = "f305871d2f381d21527c770d4788c06c097c9bc1"
uuid = "777ac1f9-54b0-4bf8-805c-2214025038e7"
version = "1.2.0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
version = "1.11.0"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "64d974c2e6fdf07f8155b5b2ca2ffa9069b608d9"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.2.2"

[[deps.SparseArrays]]
deps = ["Libdl", "LinearAlgebra", "Random", "Serialization", "SuiteSparse_jll"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
version = "1.11.0"

[[deps.SpecialFunctions]]
deps = ["IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "41852b8679f78c8d8961eeadc8f62cef861a52e3"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "2.5.1"

    [deps.SpecialFunctions.extensions]
    SpecialFunctionsChainRulesCoreExt = "ChainRulesCore"

    [deps.SpecialFunctions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[[deps.Statistics]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "ae3bb1eb3bba077cd276bc5cfc337cc65c3075c0"
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
version = "1.11.1"
weakdeps = ["SparseArrays"]

    [deps.Statistics.extensions]
    SparseArraysExt = ["SparseArrays"]

[[deps.StatsAPI]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "9d72a13a3f4dd3795a195ac5a44d7d6ff5f552ff"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.7.1"

[[deps.StatsBase]]
deps = ["AliasTables", "DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "2c962245732371acd51700dbb268af311bddd719"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.34.6"

[[deps.StatsFuns]]
deps = ["HypergeometricFunctions", "IrrationalConstants", "LogExpFunctions", "Reexport", "Rmath", "SpecialFunctions"]
git-tree-sha1 = "8e45cecc66f3b42633b8ce14d431e8e57a3e242e"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "1.5.0"

    [deps.StatsFuns.extensions]
    StatsFunsChainRulesCoreExt = "ChainRulesCore"
    StatsFunsInverseFunctionsExt = "InverseFunctions"

    [deps.StatsFuns.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[[deps.StringManipulation]]
deps = ["PrecompileTools"]
git-tree-sha1 = "725421ae8e530ec29bcbdddbe91ff8053421d023"
uuid = "892a3eda-7b42-436c-8928-eab12a02cf0e"
version = "0.4.1"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.11.0"

[[deps.SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "Serialization", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[deps.SuiteSparse_jll]]
deps = ["Artifacts", "Libdl", "libblastrampoline_jll"]
uuid = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
version = "7.7.0+0"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "c06b2f539df1c6efa794486abfb6ed2022561a39"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

[[deps.Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "OrderedCollections", "TableTraits"]
git-tree-sha1 = "f2c1efbc8f3a609aadf318094f8fc5204bdaf344"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.12.1"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.10.0"

[[deps.TensorCore]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "1feb45f88d133a655e001435632f019a9a1bcdb6"
uuid = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"
version = "0.1.1"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
version = "1.11.0"

[[deps.TikzPictures]]
deps = ["LaTeXStrings", "Poppler_jll", "Requires", "tectonic_jll"]
git-tree-sha1 = "79e2d29b216ef24a0f4f905532b900dcf529aa06"
uuid = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
version = "3.5.0"

[[deps.TranscodingStreams]]
git-tree-sha1 = "0c45878dcfdcfa8480052b6ab162cdd138781742"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.11.3"

[[deps.Tricks]]
git-tree-sha1 = "372b90fe551c019541fafc6ff034199dc19c8436"
uuid = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
version = "0.1.12"

[[deps.URIs]]
git-tree-sha1 = "bef26fb046d031353ef97a82e3fdb6afe7f21b1a"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.6.1"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"

[[deps.UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Zlib_jll"]
git-tree-sha1 = "59071150afa35787c1656ba234cf03fdf8e2603f"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.13.8+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "b5899b25d17bf1889d25906fb9deed5da0c15b3b"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.8.12+0"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "aa1261ebbac3ccc8d16558ae6799524c450ed16b"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.13+0"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "52858d64353db33a56e13c341d7bf44cd0d7b309"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.6+0"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Xorg_libX11_jll"]
git-tree-sha1 = "a4c0ee07ad36bf8bbce1c3bb52d21fb1e0b987fb"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.7+0"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Xorg_libX11_jll"]
git-tree-sha1 = "7ed9347888fac59a618302ee38216dd0379c480d"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.12+0"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Xorg_libXau_jll", "Xorg_libXdmcp_jll"]
git-tree-sha1 = "bfcaf7ec088eaba362093393fe11aa141fa15422"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.17.1+0"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "a63799ff68005991f9d9491b6e95bd3478d783cb"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.6.0+0"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.13+1"

[[deps.Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "446b23e73536f84e8037f5dce465e92275f6a308"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.5.7+1"

[[deps.glmnet_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "31adae3b983b579a1fbd7cfd43a4bc0d224c2f5a"
uuid = "78c6b45d-5eaf-5d68-bcfb-a5a2cb06c27f"
version = "2.0.13+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"
version = "5.11.0+0"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Zlib_jll"]
git-tree-sha1 = "07b6a107d926093898e82b3b1db657ebe33134ec"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.50+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.59.0+0"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "17.4.0+2"

[[deps.tectonic_jll]]
deps = ["Artifacts", "Fontconfig_jll", "FreeType2_jll", "Graphite2_jll", "HarfBuzz_ICU_jll", "HarfBuzz_jll", "ICU_jll", "JLLWrappers", "Libdl", "OpenSSL_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "54867b00af20c70b52a1f9c00043864d8b926a21"
uuid = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"
version = "0.13.1+0"
"""

# ╔═╡ Cell order:
# ╠═7e72f1fc-345a-4a2d-b03b-8a7549ef6efc
# ╠═35c21158-fc55-45f6-930d-7b82c2c0685d
# ╟─d9d53d21-09ee-47cd-b661-8787de32f2c1
# ╟─842ec98f-505a-4873-9c64-725e2f92cbb9
# ╟─4509e5b8-8d54-47e1-9ba7-b4929fd2d2fc
# ╟─3b3342fd-e1f9-4bb0-ac0e-580b2ec2af2b
# ╟─81f6f055-fd51-455a-9dae-bc8a03b0d94f
# ╟─bd08b641-e332-4b9b-9a44-2aea39d80b6c
# ╟─f9089736-3744-4382-8bc0-68fc04b3cddb
# ╠═aa9782b5-88be-43a2-b1e1-d68f289a8fec
# ╠═7df1cd87-40fa-45c1-9d85-1d491c414a18
# ╠═092331da-31a4-403d-b0cb-6e7705c6d81b
# ╠═3d201819-788b-4d90-b3a6-5483fc16ca81
# ╟─5bbb5349-534a-48e2-8da5-08527784bc87
# ╟─8037f78d-8938-42fc-98a2-210b442c00f0
# ╟─7883ecc5-b01f-49d3-98c0-67676701e90e
# ╟─5dd62dd3-fc67-4043-9579-aea1b1a922a9
# ╟─ad441089-505f-4da2-a345-548e8c4dd7d2
# ╟─792e9b54-3438-4338-913c-190565d38029
# ╠═0bf44317-45cf-4899-8b1b-dfa1fe018db4
# ╠═461859c0-5f94-469c-a054-4553045bac17
# ╟─9a5bac04-d1d9-49f4-b7c4-b18bfdd436ef
# ╟─68c959c7-b8e9-4992-b4ce-a793d1a34d20
# ╟─6680a1f4-0cc5-4dc8-a0a2-f5b5014c712a
# ╟─cad88757-7a23-4c99-84fe-219d9337a1f7
# ╟─924555b0-5ddc-4ee5-ad32-4696f9fb47e4
# ╠═dce75e41-274b-4e6a-8949-5caaeef7238a
# ╠═2713503d-165f-47f9-8ece-4cd5ddc0bb21
# ╠═464f5a71-d820-4300-b062-e2eb9491f612
# ╠═59c0e9a2-ab43-45b8-83a8-e0e865b1895d
# ╠═a60daaa3-d5da-4ac5-b40b-65bbbffdae55
# ╠═4344de43-abfa-45c6-ab84-8578ba87f60f
# ╠═774ebdcf-3d88-47b8-aa66-f59822b18321
# ╠═80910abe-97df-4283-bc18-d8c8e876174e
# ╠═fc4be0cb-5531-4432-a265-30f0cc27494d
# ╠═e4d99869-844e-4c1b-a64c-9cbf1eabab99
# ╠═11ffa65f-6c38-48bd-b22b-07c238596473
# ╠═0a336d04-b2c5-45d6-b2a4-7f03666cb597
# ╟─1bc87b69-a59c-4074-b57d-011bf5e3df73
# ╠═68b24556-4731-4b8f-b8a6-7aa7ffa38a92
# ╠═9dfe9cd4-9baa-4808-9b7a-d01c62ee6d40
# ╟─b6300fcc-8073-4487-80a2-8739123c1469
# ╠═a26fd943-dd6c-4e42-b6b0-5c9a17f31b19
# ╠═ffb59613-e16b-4d38-9c36-c778f92842e0
# ╟─8fb45733-6b2b-428a-9536-fe6b6e2f2aa3
# ╠═58867c8d-af21-48e9-ab0c-4472711e8eb0
# ╠═1547ff9a-0fa8-4295-94dd-73bd3678129f
# ╠═848e19a7-73bc-40c4-98bb-310b9f9c8079
# ╟─df1f716a-f961-4f6b-821c-e1038f190449
# ╟─27465f25-d6c7-4855-a20f-1142b8cd3e9f
# ╠═aa36d8d7-a7d4-4aa4-b0ee-b07d36cc453b
# ╠═acc8d4d0-a332-478f-8630-b22a10e7063b
# ╠═3c7cddb2-72c6-45d1-a902-f66cb67d2835
# ╟─70e78f3d-a261-43b1-a590-966c7c96021c
# ╟─fe682b63-2a06-4c32-8dc0-2f99ba48a873
# ╠═f408a310-fce3-4876-819e-3457037bd48f
# ╟─ae30bfd8-6b42-4aa7-90f2-e7303b359b94
# ╠═5bdd9d83-3911-4ab5-aefb-5ead429ac5a5
# ╠═1807eb3a-ce0b-46fe-8c70-fa4af3d9ebad
# ╠═a3bf8549-fff8-4423-8a87-a81cb21f9eb1
# ╟─010a12e2-1abc-4471-a81b-005c30578e63
# ╠═dcaeb6a8-78d1-11ec-24fb-4509de0a7d7b
# ╠═6a0e653c-5a60-48d6-a3de-2c9409558b71
# ╠═442255bc-4d49-4602-b0d4-a935871a9fe8
# ╠═da873791-517d-4ac3-80f8-ceae5808be24
# ╠═322d1562-2197-4131-bd17-93aed063e55c
# ╟─cf99206b-8a78-40de-bd0d-20bb37ec0b09
# ╠═2bf78ef8-8fc5-4e0b-a7c0-f72757bae6f6
# ╟─3d1cd3b5-66f5-44a8-805a-496e801be858
# ╟─1040f2b8-3999-46fb-9e3d-c163264a4f8a
# ╠═f71dbf67-c6c2-444b-acf4-0569ee85bc6b
# ╠═565af43c-8b85-4ab4-b72d-ac9560efd4fc
# ╠═3e2460ec-102a-4d3c-a4c5-5d6c6e2193ec
# ╠═82d3a20f-ea2b-47e6-96df-45fa568da9f8
# ╠═4daad9cb-5651-4757-a390-27bbbfa5d4c9
# ╠═b4800358-212d-4efc-af6e-8bbdd53609e6
# ╠═272428e7-f865-4d9e-9df1-9fb45dec6a96
# ╠═0ac7a1d4-f9c4-4e9a-a1fd-ff7629022fad
# ╟─4dd5df1f-f0bc-49ec-a533-4498ed17d223
# ╠═208932c4-a57b-487d-9d3b-f165b4a4a4ed
# ╠═7e6ae5d6-ff89-45f5-914a-c58d3e185041
# ╠═6702fde2-8847-407b-9d69-8e099374d6ce
# ╟─b338591d-cc11-4e9e-827e-7fcee5b2d38b
# ╠═b1350eb1-059e-4f83-a539-2e2befc3dabb
# ╠═4114f8f4-51a5-4af6-b8b7-e17480d942e3
# ╠═e8e733ee-586d-4ef6-a8ad-8c793cc8e3e9
# ╠═44eddeed-1763-4c04-b213-b7469983286d
# ╠═1161cc82-6b2d-42e0-99fe-2dfb1a2d00b6
# ╠═d7dd7859-9489-4bfc-bc77-edec76fe96f2
# ╠═07a56b99-964f-499d-913b-9c2aaeae6b51
# ╠═1499710e-1316-4113-b551-83d0e01151ab
# ╟─ce416101-f2e1-4b67-a166-b099325c3be2
# ╟─6428269b-4821-48a3-b46b-38a06bf9aa1a
# ╟─d974f740-2c3e-4225-bed8-f444bccde910
# ╟─d06052d3-07c3-43b6-909d-b31b06097fd3
# ╟─0d000f59-ecb2-4fc9-9f21-c60eac17b3bf
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
