### A Pluto.jl notebook ###
# v0.20.21

#> [frontmatter]
#> title = "Lamb's Problem"
#> layout = "layout.jlhtml"
#> tags = ["pointsource"]
#> description = "Superposition of planewaves"

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    #! format: off
    return quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
    #! format: on
end

# ╔═╡ 897afffa-77e8-11ef-1a54-c73d1df8f6a4
using QuadGK, Bessels, PlutoPlotly, FFTW, Symbolics, SpecialFunctions, PlutoUI, ProgressLogging

# ╔═╡ aa38e7f6-b8d2-4270-9142-1aa688041eb4
using LinearAlgebra

# ╔═╡ 4621f804-6a44-4c46-af37-3d364ba74cfe
using Groebner, Nemo, Statistics

# ╔═╡ 9b488729-aadc-4c1d-b971-6931d4bc9a08
using HypertextLiteral: @htl

# ╔═╡ 6188ff3e-cfd5-4c9c-aa39-619dc280d494
TableOfContents()

# ╔═╡ 1bbedd43-9e69-4ba0-a251-855f1f63dcf8
md"""# Lamb's Problem — Reflectivity Method
Lamb's Problem is a classical problem in seismology and geophysics that involves understanding the response of an elastic half-space to a point source, such as an earthquake or an explosion. The notebook leverages `QuadGK` package to perform numerical integration.

The Reflectivity Method is a powerful technique used in seismology to model the propagation of seismic waves in layered media. It involves calculating the reflection and transmission coefficients of seismic waves at each interface between different layers. By superimposing these plane waves, the method can simulate the wavefield generated by a point source in a stratified medium.

##### [Interactive Seismology Notebooks](https://pawbz.github.io/Interactive-Seismology.jl/)

Instructor: *Pawan Bharadwaj*,
Indian Institute of Science, Bengaluru, India
"""

# ╔═╡ 5d8719c8-4b50-435b-9c3e-aa8eee50df98
n_layers = 5

# ╔═╡ d1f5e223-cc49-4fe8-9b2e-c1ccecf2315a
# Reference frequency for causal-Q dispersion
@bind f_ref_hz PlutoUI.Slider(0.05:0.05:5.0, default=1.0, show_value=true)

# ╔═╡ 614a3832-7bc7-4bd3-a09d-50b76afdd7cf
ω_ref = 2π * f_ref_hz

# ╔═╡ 9f5c360c-7699-4c78-8e4b-8a2d316bc304
@bind z Slider(range(0, 100, length=10), show_value=true)

# ╔═╡ d060f642-89bf-430d-a509-25133ab0aacd
z

# ╔═╡ cc9dbdc7-56a7-410e-9787-6ce75748596e
100

# ╔═╡ 7a3bd5df-0f9f-489c-b522-4098c325c0c0
md"## Conical Wave"

# ╔═╡ 29020170-3173-40a4-aac6-9d0fd1212aaf
"""
    get_vertical_wavenumber(c, p; tol=1e-10)

Compute vertical wavenumber with numerically stable branch selection.
Adds tolerance to avoid roundoff errors near critical angles.

- Propagating (p < 1/c): returns negative real root
- Evanescent (p > 1/c): returns positive imaginary root
- Near-critical: handled with tolerance
"""
function get_vertical_wavenumber(c, k, ω)
    # - Propagating: negative real root (downward convention)
    # - Evanescent: positive imaginary root (decay)
    arg = @. (ω * inv(abs2(c))) - abs2(k)
    return map(arg) do a
		a >= 0 ? -sqrt(a) : 1im * sqrt(-a)
	end
end

# ╔═╡ add5414e-8a87-4164-9c2c-a3deeb13a864
kz = get_vertical_wavenumber(1.0, 1.0, 1.0)

# ╔═╡ e2fea7d5-00a3-4796-ad51-26f2dcffa55b
md"## Medium"

# ╔═╡ 5ea371a8-8035-4ba3-ab83-a9ffa2e3d504
begin
	struct Layer
	    thickness::Float64   # km
	    vp::Float64          # km/s
	    vs::Float64          # km/s
	    rho::Float64         # g/cm³
	    Qp::Float64          # P-wave quality factor
	    Qs::Float64          # S-wave quality factor
	end
	Layer(th, vp, vs, rho) = Layer(th, vp, vs, rho, 1000.0, 1000.0)
end

# ╔═╡ d430c8ec-fa65-4e72-951e-987ba9f2f160
media = (; α₁=5.0, α₂=7.0, β₁=3.0, β₂=5.0, ρ₁=3.0, ρ₂=7.0)

# ╔═╡ f047c190-0bf3-4763-9f31-b4272e837dd2
const GUTENBERG_MODEL = [
    Layer(19.0, 6.14, 3.55, 2.74, 1000.0, 1000.0),
    Layer(19.0, 6.58, 3.80, 3.00, 1000.0, 1000.0),
    Layer(12.0, 8.20, 4.65, 3.32, 1000.0, 1000.0),
    Layer(10.0, 8.17, 4.62, 3.34, 1000.0, 1000.0),
    Layer(10.0, 8.14, 4.57, 3.35, 1000.0, 1000.0),
    Layer(10.0, 8.10, 4.51, 3.36, 1000.0, 1000.0),
    Layer(10.0, 8.07, 4.46, 3.37, 1000.0, 1000.0),
    Layer(10.0, 8.02, 4.41, 3.38, 1000.0, 1000.0),
    Layer(25.0, 7.93, 4.37, 3.39, 1000.0, 1000.0),
    Layer(25.0, 7.85, 4.35, 3.41, 1000.0, 1000.0),
    Layer(25.0, 7.89, 4.36, 3.43, 1000.0, 1000.0),
    Layer(25.0, 7.98, 4.38, 3.46, 1000.0, 1000.0),
    Layer(25.0, 8.10, 4.42, 3.48, 1000.0, 1000.0),
    Layer(25.0, 8.21, 4.46, 3.50, 1000.0, 1000.0),
    Layer(50.0, 8.38, 4.54, 3.53, 1000.0, 1000.0),
    Layer(50.0, 8.62, 4.68, 3.58, 1000.0, 1000.0),
    Layer(50.0, 8.87, 4.85, 3.62, 1000.0, 1000.0),
    Layer(50.0, 9.15, 5.04, 3.69, 1000.0, 1000.0),
    Layer(50.0, 9.45, 5.21, 3.82, 1000.0, 1000.0),
    Layer(100.0, 9.88, 5.45, 4.01, 1000.0, 1000.0),
    Layer(100.0, 10.30, 5.76, 4.21, 1000.0, 1000.0),
    Layer(100.0, 10.71, 6.03, 4.40, 1000.0, 1000.0),
    Layer(100.0, 11.10, 6.23, 4.56, 1000.0, 1000.0),
    Layer(100.0, 11.35, 6.32, 4.63, 1000.0, 1000.0)
]

# ╔═╡ 360de109-d7db-4402-bca8-5b39c6f17da9
md"## Derive Reflection Coefficients"

# ╔═╡ 687b7062-ee25-4498-948f-43b187e0ccfa
# one-way phase with overflow clamp (use for Dunkin-style propagators)
function one_way_phase(q, ω::Real, h::Real; clip=80.0)
    if !isfinite(h)
        return one(q)
    end
    atten = clamp(-ω * imag(q) * h, -clip, clip)
    phase = exp(1im * ω * real(q) * h)
    return phase * exp(atten)
end

# ╔═╡ 8902f19a-6b93-458a-9198-f2322b2f5ab5
# causal constant-Q dispersion with reference frequency
function causal_velocity(v, Q, ω, ω_ref)
    if Q <= 0 || !isfinite(Q)
        return complex(v)
    end
    ωref = max(ω_ref, 1e-5)
    α = atan(1 / Q) / π
    mag = (abs(ω) / ωref)^α
    return v * mag * (1 - 1im / (2Q))
end

# ╔═╡ 05ec38ea-3431-490c-bc38-24f8c1b2d54f
begin
    function conical_wave(k, ω, r, δz, layer, ωref)
		c = causal_velocity(layer.vp, layer.Qp, ω, ωref)
        kz = get_vertical_wavenumber(c, k, ω)
        return Bessels.besselj0.(k .* r) .* exp.(-im .* kz .* δz) .* k ./ kz ./ im
    end
    # function conical_wave(p, ωgrid, x, y, z, c1, c2, h)
    #     r = sqrt.(abs2.(x) + abs2.(y))
    #     ξ = get_vertical_wavenumber(c1, p)
    #     η = get_vertical_wavenumber(c2, p)
    #     return Bessels.besselj0.(ωgrid .* p .* r) .* exp.(im .* ωgrid .* (ξ .* h .- η .* z)) .* p / ξ
    # end
end

# ╔═╡ 7ca06983-11c1-4203-9bd0-0cc1a461b74f
function vertical_slowness(v, p)
    # Match Lamb's radiation-condition branch choice used in the Lamb notebook:
    # - Propagating: negative real root (downward convention)
    # - Evanescent: positive imaginary root (decay)
    arg = (1 / abs2(v)) - abs2(p)
    return arg >= 0 ? -sqrt(arg) : 1im * sqrt(-arg)
end

# ╔═╡ c9bf8e13-eee2-45ae-9ce5-4901c344c8f6
function wavefield_components(p, qP, qS, λ, μ, mode::Symbol, direction::Symbol)
    sign = direction == :down ? 1.0 : -1.0
    if mode == :P
        ux = 1im * p
        uz = 1im * sign * qP
        sxz = -2 * μ * p * qP * sign
        szz = -(λ * (p^2 + qP^2) + 2 * μ * qP^2)
    else
        ux = -1im * sign * qS
        uz = 1im * p
        sxz = μ * (qS^2 - p^2)
        szz = -2 * μ * sign * p * qS
    end
    return ux, uz, sxz, szz
end

# ╔═╡ e6bbca73-e59c-4b6a-854e-438222778110
# Build modal basis matrix for P-SV (columns: P↓, P↑, SV↓, SV↑)
function modal_basis_psv(layer::Layer, p, ω, ω_ref)
    vp = causal_velocity(layer.vp, layer.Qp, ω, ω_ref)
    vs = causal_velocity(layer.vs, layer.Qs, ω, ω_ref)
    rho = layer.rho
    qP = vertical_slowness(vp, p)
    qS = vertical_slowness(vs, p)
    λ, μ = rho * (vp^2 - 2vs^2), rho * vs^2

    # Columns correspond to modal eigenvectors in displacement-stress space
    col_Pd = collect(wavefield_components(p, qP, qS, λ, μ, :P, :down))
    col_Pu = collect(wavefield_components(p, qP, qS, λ, μ, :P, :up))
    col_Sd = collect(wavefield_components(p, qP, qS, λ, μ, :SV, :down))
    col_Su = collect(wavefield_components(p, qP, qS, λ, μ, :SV, :up))

    V = hcat(col_Pd, col_Pu, col_Sd, col_Su)
    return V, qP, qS
end

# ╔═╡ d60d4d65-8896-40ee-b52f-17d66999c727
"""
    compound_matrix_psv(layer::Layer, p, ω, ω_ref; is_halfspace=false)

Exact Dunkin-style propagator for P–SV using modal basis (P↓, P↑, SV↓, SV↑).
Returns exponent `exa` (for potential scaling) and 4×4 propagator `D` such that
state_out = D * state_in. Uses one-way phases with overflow clamping.
"""
function compound_matrix_psv(layer::Layer, p, ω, ω_ref; is_halfspace=false)
    if is_halfspace || !isfinite(layer.thickness)
        return 0.0, Matrix{ComplexF64}(I, 4, 4)
    end

    h = layer.thickness
    V, qP, qS = modal_basis_psv(layer, p, ω, ω_ref)

    # One-way phases for each mode (down/up)
    # Downgoing: exp(+iqωh), Upgoing: exp(-iqωh) = conjugate for real q
    phase_Pd = one_way_phase(qP, ω, h)
    phase_Pu = one_way_phase(qP, ω, -h)  # upgoing = negative distance
    phase_Sd = one_way_phase(qS, ω, h)
    phase_Su = one_way_phase(qS, ω, -h)  # upgoing = negative distance

    Phase = Diagonal([phase_Pd, phase_Pu, phase_Sd, phase_Su])

    # Full propagator via eigenbasis similarity transform
    D = V * Phase * inv(V)

    # Exponent not pulled out explicitly (already in phases)
    return 0.0, D
end

# ╔═╡ da2a2e26-f217-41e0-8485-6517af621d2a
function solve_interface(l1::Layer, l2::Layer, p, incident_mode::Symbol, incident_side::Symbol, ω, ω_ref)
    α1 = causal_velocity(l1.vp, l1.Qp, ω, ω_ref)
    β1 = causal_velocity(l1.vs, l1.Qs, ω, ω_ref)
    ρ1 = l1.rho
    α2 = causal_velocity(l2.vp, l2.Qp, ω, ω_ref)
    β2 = causal_velocity(l2.vs, l2.Qs, ω, ω_ref)
    ρ2 = l2.rho
    qP1, qS1 = vertical_slowness(α1, p), vertical_slowness(β1, p)
    qP2, qS2 = vertical_slowness(α2, p), vertical_slowness(β2, p)
    λ1, μ1 = ρ1 * (α1^2 - 2β1^2), ρ1 * β1^2
    λ2, μ2 = ρ2 * (α2^2 - 2β2^2), ρ2 * β2^2

    # incident side setup
    inc_layer, ref_layer, tran_layer = incident_side == :top ? (l1, l1, l2) : (l2, l2, l1)
    qP_inc, qS_inc = incident_side == :top ? (qP1, qS1) : (qP2, qS2)
    λ_inc, μ_inc = incident_side == :top ? (λ1, μ1) : (λ2, μ2)
    qP_tr, qS_tr = incident_side == :top ? (qP2, qS2) : (qP1, qS1)
    λ_tr, μ_tr = incident_side == :top ? (λ2, μ2) : (λ1, μ1)
    dir_inc = incident_side == :top ? :down : :up
    dir_ref = incident_side == :top ? :up : :down
    dir_tr = incident_side == :top ? :down : :up

    inc = wavefield_components(p, qP_inc, qS_inc, λ_inc, μ_inc, incident_mode, dir_inc)
    refP = wavefield_components(p, qP_inc, qS_inc, λ_inc, μ_inc, :P, dir_ref)
    refS = wavefield_components(p, qP_inc, qS_inc, λ_inc, μ_inc, :SV, dir_ref)
    trP = wavefield_components(p, qP_tr, qS_tr, λ_tr, μ_tr, :P, dir_tr)
    trS = wavefield_components(p, qP_tr, qS_tr, λ_tr, μ_tr, :SV, dir_tr)

    A = zeros(ComplexF64, 4, 4)
    b = -collect(inc)
    for (row, comps) in enumerate((refP, refS, trP, trS))
        # columns: RP, RS, TP, TS
    end
    A[:, 1] = collect(refP)
    A[:, 2] = collect(refS)
    A[:, 3] = -collect(trP)
    A[:, 4] = -collect(trS)

    x = A \ b
    R = x[1:2]
    T = x[3:4]
    return R, T
end

# ╔═╡ 43c34152-fc5f-4497-882f-7f42bd4e6b99
function zoeppritz_interface(l1::Layer, l2::Layer, p, ω, ω_ref)
    Rdown = zeros(ComplexF64, 2, 2)
    Tdown = zeros(ComplexF64, 2, 2)
    Rup = zeros(ComplexF64, 2, 2)
    Tup = zeros(ComplexF64, 2, 2)
    for (j, mode) in enumerate((:P, :SV))
        r1, t1 = solve_interface(l1, l2, p, mode, :top, ω, ω_ref)
        r2, t2 = solve_interface(l1, l2, p, mode, :bottom, ω, ω_ref)
        Rdown[:, j] = r1
        Tdown[:, j] = t1
        Rup[:, j] = r2
        Tup[:, j] = t2
    end
    return Rdown, Tdown, Rup, Tup
end

# ╔═╡ f25f798f-0ecc-4931-b8b5-9c958b83850f
# ...existing code...

"""
    reflectivity_pp(layers::Vector{Layer}, p, ω, ω_ref)

P→P reflectivity seen at the top of layer 1 (just below the free surface),
for a unit downgoing P in layer 1. Uses Kennett-style R/T recursion.
"""
function reflectivity_pp(layers::Vector{Layer}, p, ω, ω_ref)
    N = length(layers)
    if N <= 1
        return 0.0 + 0.0im  # no interface → no reflection
    end
	if(iszero(ω))
		return 0.0
	end
    # Effective reflection matrix looking into stack below top of halfspace
    Rplus = zeros(ComplexF64, 2, 2)  # at top of halfspace: no reflection

    for ℓ in (N - 1):-1:1
        # Propagate down and up through the lower layer (ℓ+1)
        lay_dn = layers[ℓ + 1]
        E = Matrix{ComplexF64}(I, 2, 2)
        if isfinite(lay_dn.thickness)
            vp = causal_velocity(lay_dn.vp, lay_dn.Qp, ω, ω_ref)
            vs = causal_velocity(lay_dn.vs, lay_dn.Qs, ω, ω_ref)
            qP = vertical_slowness(vp, p)
            qS = vertical_slowness(vs, p)
            eP = one_way_phase(qP, ω, lay_dn.thickness)
            eS = one_way_phase(qS, ω, lay_dn.thickness)
            E = Diagonal([eP, eS]) |> Matrix
        end
        Rbar = E * Rplus * E

        # Interface ℓ ↔ ℓ+1 Zoeppritz blocks (2×2 each)
        Rd, Td, Ru, Tu = zoeppritz_interface(layers[ℓ], layers[ℓ + 1], p, ω, ω_ref)

        # Kennett recursion: R_top = Rd + Td * Rbar * (I - Ru*Rbar)^-1 * Tu
        Den = I - Ru * Rbar
        Rplus = Rd + Td * (Rbar * (Den \ Tu))
    end

    return Rplus[1, 1]  # P←P element at the top of layer 1
end

# ...existing code...

# ╔═╡ dea0645d-cb7c-4488-913b-ba225595aceb
begin
	# // Test homogeneous halfspace
	test_layers_homo = [Layer(Inf, 6.0, 3.5, 2.7)]
	
	# Test across different ray parameters and frequencies
	p_test = [0.0, 0.05, 0.1, 0.15, 0.19]
	f_test = 1.0
	ω_test = 2π * f_test
	
	for p in p_test
	    Rpp = reflectivity_pp(test_layers_homo, p, ω_test, ω_ref)
	    println("p=$p: Rpp = $Rpp (should be ~0)")
	end
end

# ╔═╡ 579cfd9f-e872-4ec5-b913-c90f8e183247
begin
	test_layers_2 = [
	    Layer(40.0, 4.0, 3.0, 2.5), 
		  Layer(10.0, 5.0, 3.0, 2.5),# Layer 1
	    Layer(Inf, 6.0, 3.5, 2.7)     # Halfspace
	]
	
	# Critical angle for P-wave: p_crit = 1/v_p = 1/6.0 ≈ 0.167
	p_crit = 1.0 / 6.0
	
	p_range = range(0, p_crit * 1.2, length=50)
	Rpp_vals = [angle(reflectivity_pp(test_layers_2, p, 2π*1.0, ω_ref)) for p in p_range]
	
	plot(p_range, Rpp_vals, xlabel="Ray Parameter p (s/km)", ylabel="|Rpp|")
end

# ╔═╡ a1e5796b-6f2f-44c6-b5bf-df6c9ee20960
let
	test_layers = [
	    Layer(20.0, 5.0, 3.0, 2.5),
		Layer(20.0, 5.0, 5.0, 2.5),
	    Layer(Inf, 7.0, 4.0, 3.0)
	]
	
	p_test = range(0, 0.19, length=100)
	Rpp_test = [reflectivity_pp(test_layers, p, 2π*1.0, ω_ref) for p in p_test]
	
	max_abs = maximum(abs.(Rpp_test))
	println("Max |Rpp| = $max_abs (should be ≤ 1.0)")
end

# ╔═╡ 55e64939-9298-4a15-a2b0-0d13c23d03dc
let
	# Normal incidence reflection coefficient
	function normal_incidence_pp(layer1, layer2)
	    z1 = layer1.rho * layer1.vp
	    z2 = layer2.rho * layer2.vp
	    return (z2 - z1) / (z2 + z1)
	end
	
	test_layers = [
	    Layer(10.0, 5.0, 3.0, 2.5),
	    Layer(Inf, 6.0, 3.5, 2.7)
	]
	
	# Analytical
	R_analytical = normal_incidence_pp(test_layers[1], test_layers[2])
	
	# From reflectivity function
	R_numerical = reflectivity_pp(test_layers, 0.0, 2π*1.0, ω_ref)
	
	println("Analytical Rpp(p=0) = $R_analytical")
	println("Numerical Rpp(p=0) = $R_numerical")
	println("Difference: $(abs(R_analytical - R_numerical))")
end

# ╔═╡ 1d49ebac-04a4-44a5-890c-f565d34246c1
let
	test_layers = [
	    Layer(10.0, 5.0, 3.0, 2.5),
		Layer(10.0, 4.0, 3.0, 2.5),
	    Layer(Inf, 6.0, 3.5, 2.7)
	]
	
	p_test = 0.1
	freq_range = [0.1, 0.5, 1.0, 2.0, 5.0]
	
	for f in freq_range
	    Rpp = reflectivity_pp(test_layers, p_test, 2π*f, ω_ref)
	    println("f=$f Hz: Rpp = $Rpp")
	end
end

# ╔═╡ 12104212-be60-42e8-85ba-518555ca31f2
let
	test_layers = [
	    Layer(10.0, 5.0, 3.0, 2.5),
	    Layer(Inf, 6.0, 3.5, 2.7)
	]
	
	Rpp = reflectivity_pp(test_layers, 0.1, 2π*1.0, ω_ref)
	
	println("Rpp = $Rpp")
	println("|Rpp| = $(abs(Rpp))")
	println("Phase = $(angle(Rpp)) rad = $(rad2deg(angle(Rpp))) deg")
end

# ╔═╡ 3dfbfc66-8f87-4906-84f5-495bf113e4ef


# ╔═╡ 0de7835c-eb50-4de0-874b-e08270d988aa
@syms α₁ β₁ ρ₁ α₂ β₂ ρ₂

# ╔═╡ 8ef12535-49a1-46fe-a26c-880358755a16
@variables Aₚ Aₛ Bₚ Bₛ

# ╔═╡ c077d6f7-9fc7-4c0b-bf42-26882a374cbf
@variables ı

# ╔═╡ 68e54426-2a9f-409c-acd9-e0e6e9681487
plane_wave(p, η, A) = A * exp(ı * ω * (t - (p * x + η * z)))

# ╔═╡ 4c8103ff-8928-4c78-ad63-d0175738ef7f
incident_potential = plane_wave(p, ξ₁, 1.0)

# ╔═╡ e2438fc6-78e9-4d06-9e4c-ee4ff22d0062
reflected_P_potential = plane_wave(p, -ξ₁, Aₚ)

# ╔═╡ 0ee489a5-3769-4bdf-9e88-cdf54199d692
reflected_S_potential = plane_wave(p, -ν₁, Aₛ)

# ╔═╡ 75fc91ce-840f-4625-87eb-1870f668f5c0
transmitted_P_potential = plane_wave(p, ξ₂, Bₚ)

# ╔═╡ 03a80695-170a-4a2f-a124-630dc3dbf5b6
transmitted_S_potential = plane_wave(p, ν₂, Bₛ)

# ╔═╡ 99ee6828-0a0d-4048-8ffd-d25b7848368b
begin
    Dx = Differential(x)
    Dz = Differential(z)
end

# ╔═╡ 8fe6d5f7-7ec9-4a67-a557-ffe51124066b
begin
    uxInc = expand_derivatives.(Dx(incident_potential))
    uzInc = expand_derivatives.(Dz(incident_potential))
end

# ╔═╡ 277a6190-3f6e-4008-aa2c-aac84d205f42
begin
    uxRefP = expand_derivatives.(Dx.(reflected_P_potential))
    uzRefP = expand_derivatives.(Dz.(reflected_P_potential))
    uxRefS = expand_derivatives.(-Dz.(reflected_S_potential))
    uzRefS = expand_derivatives.(Dx.(reflected_S_potential))
end

# ╔═╡ 1d58e672-5c50-4000-8842-7c592b22c32e
begin
    uxTransP = expand_derivatives.(Dx.(transmitted_P_potential))
    uzTransP = expand_derivatives.(Dz.(transmitted_P_potential))
    uxTransS = expand_derivatives.(-Dz.(transmitted_S_potential))
    uzTransS = expand_derivatives.(Dx.(transmitted_S_potential))
end

# ╔═╡ 65c2f4a8-92f7-4673-ba7a-ba2367b558aa
σzz1 = (expand_derivatives(λ₁ .* Dx.(uxInc + uxRefP + uxRefS) .+ (λ₁ + 2 * μ₁) .* Dz.(uzInc + uzRefP + uzRefS)))

# ╔═╡ ae0e4d63-8348-46ac-994f-11b1ce1001fb
σzz2 = (expand_derivatives(λ₂ .* Dx.(uxTransP + uxTransS) .+ (λ₂ + 2 * μ₂) .* Dz.(uzTransP + uzTransS)))

# ╔═╡ 7b55d65d-7654-4ac5-9b3c-d0f8b52905cd
σxz1 = (expand_derivatives.(μ₁ .* Dx.(uzInc + uzRefP + uzRefS) .+ μ₁ .* Dz.(uxInc + uxRefP + uxRefS)))

# ╔═╡ 0e3d2a52-e357-4b54-80ce-fb7f44c6334f
σxz2 = (expand_derivatives.(μ₂ .* Dx.(uzTransP + uzTransS) .+ μ₂ .* Dz.(uxTransP + uxTransS)))

# ╔═╡ 060c9127-775a-45c0-b31b-2a6dcacac179
Ux_constraint = uxInc + uxRefP + uxRefS - uxTransP - uxTransS

# ╔═╡ 0f034701-7953-4428-bde9-b2a21fbc5c6e
Uz_constraint = uzInc + uzRefP + uzRefS - uzTransP - uzTransS

# ╔═╡ 52149e10-3a89-412a-bd43-e29e26592551
Ux_z0 = simplify(substitute(Ux_constraint, z => 0) / ω / ı / exp(ı * ω * (t - p * x)))

# ╔═╡ 94fc6b36-7e38-4fc1-af47-9c82d6595e6b
Uz_z0 = simplify(substitute(Uz_constraint, z => 0) / ω / ı / exp(ı * ω * (t - p * x)))

# ╔═╡ cca1bbd7-5455-47f9-bef9-448ece10c2b6
σzz_constraint = σzz1 - σzz2

# ╔═╡ d94908f6-1d0f-46ff-8c8e-ef0d407b539d
σzz_z0 = simplify(substitute(σzz_constraint, [z => 0, ı^2 => -1]) / ω^2 / exp(ı * ω * (t - p * x)))

# ╔═╡ a015f013-7333-44e7-b7bb-a293aefeac0b
σxz_constraint = σxz1 - σxz2

# ╔═╡ 3aaca98b-4b75-4970-97cf-b4649f443017
σxz_z0 = simplify(substitute(σxz_constraint, [ı^2 => -1, z => 0]) / ω^2 / exp(ı * ω * (t - p * x)))

# ╔═╡ 93d2f1ad-06ed-4080-a0ce-5ec1eb642e4e
function subs(ex, media)
    α₁, α₂, β₁, β₂, ρ₁, ρ₂ = media
    ex = simplify(substitute(ex, [ı^2 => -1, λ₁ => ρ₁ * (α₁^2 - 2 * β₁^2), μ₁ => β₁^2 * ρ₁, λ₂ => ρ₂ * (α₂^2 - 2 * β₂^2), μ₂ => β₂^2 * ρ₂,
        ξ₁^2 => (1 / α₁^2 - p^2), ξ₂^2 => (1 / α₂^2 - p^2), ν₁^2 => (1 / β₁^2 - p^2), ν₂^2 => (1 / β₂^2 - p^2)]))
    ex = simplify(substitute(ex, [α₁ => α₁, α₂ => α₂, β₁ => β₁, β₂ => β₂, ρ₁ => ρ₁, ρ₂ => ρ₂]))
    return ex
end

# ╔═╡ 02237fbb-f2d3-4436-ad0e-c60df62befaa
function get_A(f, p1, media)
    α₁, α₂, β₁, β₂, ρ₁, ρ₂ = media
    ξ₁p = get_vertical_wavenumber(α₁, p1)
    ξ₂p = get_vertical_wavenumber(α₂, p1)
    ν₁p = get_vertical_wavenumber(β₁, p1)
    ν₂p = get_vertical_wavenumber(β₂, p1)
    return Complex{Float64}(f(p1, ξ₁p, ξ₂p, ν₁p, ν₂p))
    # ex = simplify(substitute(ex, [p=>]))
end

# ╔═╡ 239a50ff-3970-47ff-b772-fc3e0cb247fe
function solve_linear_AB(media)
    constraints = [σzz_z0, σxz_z0, Ux_z0, Uz_z0]
    Avec = Symbolics.symbolic_linear_solve(constraints, [Aₚ, Bₚ, Aₛ, Bₛ])
	@show Avec
    # Avec = Symbolics.symbolic_solve(constraints, [Aₚ, Bₚ, Aₛ, Bₛ])
    Avec_subs = Dict(string(key) => subs(Avec[1][key], media) for key in keys(Avec[1]))
end

# ╔═╡ fa4b8951-569e-4517-9b0a-f77a22a31fca
begin
    Avec = solve_linear_AB(media)
    # Afunctions_vec = Dict(string(key) => build_function(Avec[key], p, ξ₁, ξ₂, ν₁, ν₂, expression=Val{false}) for key in keys(Avec))
end;

# ╔═╡ f0a4c439-ee9b-4001-97db-66f6ac5afd5a
md"## Sommerfeld Integral"

# ╔═╡ 0e8564a1-d300-4ca1-84f3-93ebea6ad08a
struct Direct end

# ╔═╡ e1908cc5-a4c1-4802-9f23-d9905a68cc36
struct Preflect end

# ╔═╡ 281a5cac-4e00-42d6-b331-ea5d80888f27
struct Sreflect end

# ╔═╡ 4e31b3c7-e7ab-4a10-ba04-292dd03a3732
md"""Select the term $(@bind plot_phase confirm(Select([Direct() => "Direct", Preflect() => "Reflected P",  Sreflect() => "Reflected S"])))"""

# ╔═╡ 089b0602-077a-4074-a424-0a6afab8bcf4
"""
    smooth_taper(p, p_max)

Smooth cosine (Tukey-style) window near the upper limit p_max.
Keeps full amplitude for p ≤ p_max(1-width), then tapers to 0 at p_max.
"""
function smooth_taper(p, p_max; width=0.3)
    if p <= p_max * (1 - width)
        return 1.0
    elseif p < p_max
        # Map [p_max(1-width), p_max] → [0, π]
        t = π * (p - p_max * (1 - width)) / (width * p_max)
        return 0.5 * (1.0 + cos(t))
    else
        return 0.0
    end
end

# ╔═╡ 72aca1bf-3997-4be3-b316-921b45480c1a
md"## Seismograms"

# ╔═╡ 12f7733a-edd6-481f-8166-ef967520b35a
seismograms_param = let
    Nt = 512
    freq_snapshot = 1.0
    tgrid = range(0, 100, length=Nt)
    ωgrid = collect(rfftfreq(Nt, inv(step(tgrid)))) * 2.0 * pi
    f0 = freq_snapshot
    ω0 = 2.0 * pi * f0
    rgrid = collect(range(-100, 100, length=100))
    # ΩR = collect(Iterators.product(ωgrid, rgrid))
    Ω = reshape(ωgrid, :, 1)
    R = reshape(rgrid, 1, :)
    Z = fill(z, size(R))
    W = @. exp(-0.1(Ω - ω0)^2)
    (; Nt, Ω, R, Z, W, rgrid, tgrid, ωgrid, ω0, f0)
end;

# ╔═╡ 210c693b-e0a2-4660-9389-bdc3e410080a
Bessels.besselj0.(1.0 .* seismograms_param.R) .* exp.(im .* kz)

# ╔═╡ 3f8684cb-03c7-4c86-86b5-0af2d9a32418
@time conical_wave(0.0, seismograms_param.Ω, seismograms_param.X, seismograms_param.Y, seismograms_param.Z, media.α₁ + 1e-3)

# ╔═╡ a88a10fe-2a02-458d-898a-25cdb0d15af4
conical_wave(0.1, seismograms_param.Ω, seismograms_param.X, seismograms_param.Y, seismograms_param.Z, media.α₁)

# ╔═╡ f73569cb-ef42-432a-8910-cbb0176cea18
seismograms_param.Ω

# ╔═╡ 37e33e90-0d44-4a9d-abeb-a7ee1cf9f977
seismograms_param.Z

# ╔═╡ 3693ffe9-979b-416a-85de-8438f00a6fc2
H1 = 100.0

# ╔═╡ 765b90b8-060d-4b68-8201-309abe4adebc
first.(Iterators.product(1:10, 11:20))

# ╔═╡ 6923e13d-a4c5-45c9-a1b2-f0104932d709
function remove_zero_frequency!(C)
	C[1, :] .= 0.0
	return C
end

# ╔═╡ 4b283a44-214a-4bc0-8eb9-031a0e124a82
md"## Snapshot"

# ╔═╡ e91921c5-4600-4344-85c7-e35820ba2daa
snapshot_param = let
    N = 101
    freq_snapshot = 1.0
    zgrid = range(5, stop=99, length=N)
    xgrid = range(-200, stop=200, length=N)
    ZX = collect(Iterators.product(zgrid, xgrid))
    Z = vec(first.(ZX))
    X = vec(last.(ZX))
    Y = fill(0.0, length(X))
    Ω = fill(2 * pi * freq_snapshot, length(X))
    W = fill(1.0, length(X))
    (; X, Y, Z, Ω, W, N, xgrid, zgrid)
end;

# ╔═╡ c695e4d3-c49d-4587-8adc-cdd4c001325e
md"## Appendix"

# ╔═╡ fbd2b939-c816-42dd-a65e-94abce3dc91a
default_plotly_template(:plotly_dark)

# ╔═╡ af2ca94f-f684-4df7-90de-f1e699004e0f
function layer_table_input(n_layers::Int, defaults::Vector{Layer}; vp_vs_ratio=1.73)
    ui = PlutoUI.combine() do Child
        header = @htl("""
        <tr style=\"text-align:center;\">
          <th style=\"padding:6px;\">#</th>
          <th style=\"padding:6px;\">Thickness (km)</th>
          <th style=\"padding:6px;\">Vp (km/s)</th>
          <th style=\"padding:6px;\">Vs (km/s)</th>
          <th style=\"padding:6px;\">Density (g/cc)</th>
        </tr>
        """)

        rows = Any[]
        for i in 1:n_layers
            layer = i <= length(defaults) ? defaults[i] : defaults[end]
            tw = i < n_layers ? Child("thickness_$i", Slider(0.25:0.25:60.0, default=layer.thickness, show_value=true)) : "∞"
            vpw = Child("vp_$i", Slider(2.0:0.05:9.0, default=layer.vp, show_value=true))
            vsw = Child("vs_$i", Slider(0.5:0.05:5.5, default=layer.vs, show_value=true))
            rw = Child("rho_$i", Slider(1.5:0.05:4.0, default=layer.rho, show_value=true))

            push!(rows, @htl("""
                <tr>
                  <td style=\"text-align:center; padding:6px;\"><b>Layer $i</b></td>
                  <td style=\"padding:6px; text-align:center;\">$tw</td>
                  <td style=\"padding:6px; text-align:center;\">$vpw</td>
                  <td style=\"padding:6px; text-align:center;\">$vsw</td>
                  <td style=\"padding:6px; text-align:center;\">$rw</td>
                </tr>
            """))
        end

        tbl = @htl("""
        <table style=\"border-collapse:collapse; border:1px solid #ddd; width:100%;\">
          <thead>$header</thead>
          <tbody>
            $(rows...)
          </tbody>
        </table>
        """)

        md"""
        ### Layer Editor (slider mode)
        Number of layers: **$n_layers**

        $tbl
        _Last layer is a half-space (∞ thickness)._"""
    end

    return PlutoUI.Experimental.transformed_value(ui) do vals
        layers = [
            begin
                if i < n_layers
                    t = vals[4*(i-1)+1]
                    vp = vals[4*(i-1)+2]
                    vs = vals[4*(i-1)+3]
                    ρ = vals[4*(i-1)+4]
                else
                    t = Inf
                    vp = vals[4*(i-1)+1]
                    vs = vals[4*(i-1)+2]
                    ρ = vals[4*(i-1)+3]
                end
                Layer(t, vp, vs, ρ)
            end
            for i in 1:n_layers
        ]
        return layers
    end
end



# ╔═╡ 78d77dbb-1f2c-4b7c-a1ce-fa775ac7bd5c
@bind layers_ui layer_table_input(n_layers, GUTENBERG_MODEL)

# ╔═╡ d24ceb91-f463-497f-a914-5c6e90e766ee
layers_ui

# ╔═╡ ccec9a65-e249-4d28-bacb-6b53f8bfabf4
reflectivity_pp(layers_ui, 0.0, 0.01, ω_ref)

# ╔═╡ 00a3df8b-9642-461a-8d37-9342c121240e
reflectivity_pp.(Ref(layers_ui), 0.1, seismograms_param.ωgrid, ω_ref)

# ╔═╡ 84209251-8b66-4d63-ba8f-1b7c1a12b382
layers_ui[1].vp

# ╔═╡ 951a5946-ab54-4aff-be89-b8d5ea90fa1a
begin
    function get_phase(::Direct, k, kmax, param, layers)
		taper = smooth_taper(k, kmax; width=0.2)
		vp = causal_velocity(layers[1].vp, layers[1].Qp, )
        C = taper * conical_wave(k, param.Ω, param.R, param.Z, layers[1].vp)
		return C
    end
	function get_phase(::Preflect, p, p_max, param, media)
    taper = smooth_taper(p, p_max; width=0.1)
#     # frequency‑dependent reflectivity
    A = cat(reflectivity_pp.(Ref(layers_ui), p, param.ωgrid, Ref(ω_ref)), dims=2)
	C = conical_wave(p, param.Ω, param.R, param.Z, media.α₁)
	C = reshape(C, length(param.ωgrid), length(param.rgrid))
	return A .* C
#     return A .* taper .* conical_wave(p, param.Ω, param.X, param.Y, param.Z, media.α₁, h)
end
	# ...existing code...
# function get_phase(::Preflect, p, p_max, param, media, h)
#     taper = smooth_taper(p, p_max; width=0.1)

#     # Frequency‑dependent plane‑wave reflectivity of the stack at the top of layer 1
#     # A = reflectivity_pp.(Ref(layers_ui), p, param.Ω, Ref(ω_ref))
# 	A = reflectivity_pp(layers_ui, p, 1.0, 1.0)

#     # Missing two‑way vertical phase in the top medium (P in layer 1):
#     # down from source depth h to the free surface, then up to receiver depth z
#     # -> exp(i ω q1 (h + z)).  With z = 0, this becomes exp(i ω q1 2h) when
#     # combined with conical_wave’s exp(i ω q1 (h - z)).
#     q1 = get_vertical_wavenumber(media.α₁, p)  # match conical_wave’s branch/convention
#     extra_top_phase = exp.(1im .* param.Ω .* q1 .* (h .+ param.Z))

#     return A .* taper .* extra_top_phase .* conical_wave(p, param.Ω, param.X, param.Y, param.Z, media.α₁, h)
# end
# ...existing code...

	
	
  #   function get_phase(::Preflect, p, p_max, param, media, h)
		# taper = smooth_taper(p, p_max; width=0.1)
		
  #       # A = get_A(Afunctions_vec["Aₚ"], p, media)
  #       return A * taper * (conical_wave(p, param.Ω, param.X, param.Y, param.Z, media.α₁, h))
  #   end

	
    function get_phase(::Sreflect, p, p_max, param, media, h)
		taper = smooth_taper(p, p_max; width=0.1)
        A = get_A(Afunctions_vec["Aₛ"], p, media)
        return A * taper * (conical_wave(p, param.Ω, param.R, param.Z, media.α₁, media.β₁, h))
    end
end

# ╔═╡ c246fdfc-321c-4856-8a4b-cf6cb4ba1594
function get_wavefield(param, layers, phase; np=1024, pmargin=1.5)
    # Discrete Riemann summation over horizontal wavenumber in [0, kmax]

	vmax = maximum(getfield.(layers, :vs))
    kmax = maximum(param.ωgrid) / vmax * 1.2
    kgrid = range(0, kmax, length = np)

    dk = step(kgrid)

    # Accumulate vector result over all frequencies/receivers
    integral_sum = zeros(ComplexF64, length(param.ωgrid), length(param.rgrid))

    for k in kgrid
        # get_phase broadcasts over param fields and returns a vector
        integral_sum .+= get_phase(phase, k, kmax, param, layers) * dk
    end

    U = param.W .* integral_sum
    return U
end

# ╔═╡ 423c7abb-f274-4010-bd08-95adc5890204
# ╠═╡ disabled = true
#=╠═╡
snapshot = reshape(get_wavefield(snapshot_param, H1, media, plot_phase), snapshot_param.N, snapshot_param.N);
  ╠═╡ =#

# ╔═╡ a7b582ba-57fa-4f90-b017-5a9d059c30e5
#=╠═╡
plot(contour(x=snapshot_param.xgrid, y=snapshot_param.zgrid, z=log.(abs.(snapshot))), Layout(title="Radiation", yaxis_autorange="reversed", height=300, width=650))
  ╠═╡ =#

# ╔═╡ 9a9a1d8e-df81-4aa2-b0f3-49cb90f8a398
layers_ui[1]

# ╔═╡ 395d3a63-b7b8-44b5-97ab-740c4849db26
begin
	vmax = maximum(getfield.(layers_ui, :vs))
	    kmax = maximum(seismograms_param.ωgrid) / vmax * 1.2
	    # kgrid = range(0, kmax, length = 1024)
end

# ╔═╡ d297ea1c-e0ad-4fe7-bbc2-fc7d6269f8ba
get_phase(Direct(), 1.0, 4.0, seismograms_param, layers_ui)

# ╔═╡ 70ff038f-e684-4fde-8c93-0358b0181c01
C = get_wavefield(seismograms_param, layers_ui, plot_phase)

# ╔═╡ 77032c75-0cae-48a0-a5f0-7ca4de2ff3ea
C

# ╔═╡ 53a45db3-8571-4fc7-a855-5173030b7cb9
seismograms = irfft(remove_zero_frequency!(get_wavefield(seismograms_param, layers_ui, plot_phase)), seismograms_param.Nt, 1);

# ╔═╡ 96556fec-4bea-4132-946a-92d17372df54
let
    U = seismograms
    Umaxclip = maximum(abs, U) * .1
    plot(heatmap(y=seismograms_param.tgrid, x=seismograms_param.rgrid, z=U, zmin=-Umaxclip, zmax=Umaxclip, colorscale=:seismic,), Layout(title="Seismograms", width=300, yaxis_autorange="reversed", xaxis=attr(title="distance to receiver"), yaxis=attr(title="time (s)")))
end

# ╔═╡ 4ff2ef66-06eb-4df0-b491-10ab7a81d65d
seismograms

# ╔═╡ b3d2ba8e-7a02-4af1-9e4a-d9ab1b4676df
plot(seismograms[:, 6])

# ╔═╡ 47c0c813-08a2-4173-9853-f12874449b6e
seismograms

# ╔═╡ e7c1cbf4-7939-45a2-a754-b36ae9bdcab4
md"""### To Do
- Use in place functions while performing numerical integration for speedup
- Better snapshots (time dependent) to visualize generation of e.g., headwaves
- Plot displacement field, instead of potentials
- Add free surface to get Rayleigh waves?
- Response from a stack of layers...
"""

# ╔═╡ 9d10ab94-38d5-406e-8697-7f5bc0c11df2
md"""### References
- Fuchs, K., and Gerhard Müller. "Computation of synthetic seismograms with the reflectivity method and comparison with observations." Geophysical Journal International 23.4 (1971): 417-433.
"""

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
PlutoPlotly = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Bessels = "~0.2.8"
FFTW = "~1.10.0"
Groebner = "~0.10.0"
HypertextLiteral = "~0.9.5"
Nemo = "~0.52.2"
PlutoPlotly = "~0.6.5"
PlutoUI = "~0.7.72"
ProgressLogging = "~0.1.5"
QuadGK = "~2.11.2"
SpecialFunctions = "~2.6.1"
Symbolics = "~6.56.0"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "8ba07bdbf4aab40a52233abcfc7f636bf7a1184d"

[[deps.ADTypes]]
git-tree-sha1 = "27cecae79e5cc9935255f90c53bb831cc3c870d7"
uuid = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
version = "1.18.0"

    [deps.ADTypes.extensions]
    ADTypesChainRulesCoreExt = "ChainRulesCore"
    ADTypesConstructionBaseExt = "ConstructionBase"
    ADTypesEnzymeCoreExt = "EnzymeCore"

    [deps.ADTypes.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
    EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"

[[deps.AbstractAlgebra]]
deps = ["LinearAlgebra", "MacroTools", "Preferences", "Random", "RandomExtensions", "SparseArrays"]
git-tree-sha1 = "dc5edff637f5e6737128ea226c32fa242ebba3c0"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.47.3"
weakdeps = ["Test"]

    [deps.AbstractAlgebra.extensions]
    TestExt = "Test"

[[deps.AbstractFFTs]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "d92ad398961a3ed262d8bf04a1a2b8340f915fef"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "1.5.0"
weakdeps = ["ChainRulesCore", "Test"]

    [deps.AbstractFFTs.extensions]
    AbstractFFTsChainRulesCoreExt = "ChainRulesCore"
    AbstractFFTsTestExt = "Test"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "6e1d2a35f2f90a4bc7c2ed98079b2ba09c35b83a"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.3.2"

[[deps.AbstractTrees]]
git-tree-sha1 = "2d9c9a55f9c93e8887ad391fbae72f8ef55e1177"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.4.5"

[[deps.Accessors]]
deps = ["CompositionsBase", "ConstructionBase", "Dates", "InverseFunctions", "MacroTools"]
git-tree-sha1 = "3b86719127f50670efe356bc11073d84b4ed7a5d"
uuid = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
version = "0.1.42"

    [deps.Accessors.extensions]
    AxisKeysExt = "AxisKeys"
    IntervalSetsExt = "IntervalSets"
    LinearAlgebraExt = "LinearAlgebra"
    StaticArraysExt = "StaticArrays"
    StructArraysExt = "StructArrays"
    TestExt = "Test"
    UnitfulExt = "Unitful"

    [deps.Accessors.weakdeps]
    AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
    IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
    LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
    StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
    StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.Adapt]]
deps = ["LinearAlgebra", "Requires"]
git-tree-sha1 = "7e35fca2bdfba44d797c53dfe63a51fabf39bfc0"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "4.4.0"
weakdeps = ["SparseArrays", "StaticArrays"]

    [deps.Adapt.extensions]
    AdaptSparseArraysExt = "SparseArrays"
    AdaptStaticArraysExt = "StaticArrays"

[[deps.AliasTables]]
deps = ["PtrArrays", "Random"]
git-tree-sha1 = "9876e1e164b144ca45e9e3198d0b689cadfed9ff"
uuid = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
version = "1.1.3"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.2"

[[deps.ArrayInterface]]
deps = ["Adapt", "LinearAlgebra"]
git-tree-sha1 = "d81ae5489e13bc03567d4fbbb06c546a5e53c857"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "7.22.0"

    [deps.ArrayInterface.extensions]
    ArrayInterfaceBandedMatricesExt = "BandedMatrices"
    ArrayInterfaceBlockBandedMatricesExt = "BlockBandedMatrices"
    ArrayInterfaceCUDAExt = "CUDA"
    ArrayInterfaceCUDSSExt = ["CUDSS", "CUDA"]
    ArrayInterfaceChainRulesCoreExt = "ChainRulesCore"
    ArrayInterfaceChainRulesExt = "ChainRules"
    ArrayInterfaceGPUArraysCoreExt = "GPUArraysCore"
    ArrayInterfaceMetalExt = "Metal"
    ArrayInterfaceReverseDiffExt = "ReverseDiff"
    ArrayInterfaceSparseArraysExt = "SparseArrays"
    ArrayInterfaceStaticArraysCoreExt = "StaticArraysCore"
    ArrayInterfaceTrackerExt = "Tracker"

    [deps.ArrayInterface.weakdeps]
    BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
    BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
    CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
    CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
    ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
    Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
    ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
    Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.Atomix]]
deps = ["UnsafeAtomics"]
git-tree-sha1 = "29bb0eb6f578a587a49da16564705968667f5fa8"
uuid = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
version = "1.1.2"

    [deps.Atomix.extensions]
    AtomixCUDAExt = "CUDA"
    AtomixMetalExt = "Metal"
    AtomixOpenCLExt = "OpenCL"
    AtomixoneAPIExt = "oneAPI"

    [deps.Atomix.weakdeps]
    CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
    Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
    OpenCL = "08131aa3-fb12-5dee-8b74-c09406e224a2"
    oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

[[deps.Bessels]]
git-tree-sha1 = "4435559dc39793d53a9e3d278e185e920b4619ef"
uuid = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
version = "0.2.8"

[[deps.Bijections]]
git-tree-sha1 = "a2d308fcd4c2fb90e943cf9cd2fbfa9c32b69733"
uuid = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
version = "0.2.2"

[[deps.ChainRulesCore]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "e4c6a16e77171a5f5e25e9646617ab1c276c5607"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "1.26.0"
weakdeps = ["SparseArrays"]

    [deps.ChainRulesCore.extensions]
    ChainRulesCoreSparseArraysExt = "SparseArrays"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "ColorVectorSpace", "Colors", "FixedPointNumbers", "PrecompileTools", "Random"]
git-tree-sha1 = "b0fd3f56fa442f81e0a47815c92245acfaaa4e34"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.31.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "67e11ee83a43eb71ddc950302c53bf33f0690dfe"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.12.1"
weakdeps = ["StyledStrings"]

    [deps.ColorTypes.extensions]
    StyledStringsExt = "StyledStrings"

[[deps.ColorVectorSpace]]
deps = ["ColorTypes", "FixedPointNumbers", "LinearAlgebra", "Requires", "Statistics", "TensorCore"]
git-tree-sha1 = "8b3b6f87ce8f65a2b4f857528fd8d70086cd72b1"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.11.0"
weakdeps = ["SpecialFunctions"]

    [deps.ColorVectorSpace.extensions]
    SpecialFunctionsExt = "SpecialFunctions"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "37ea44092930b1811e666c3bc38065d7d87fcc74"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.13.1"

[[deps.Combinatorics]]
git-tree-sha1 = "08c8b6831dc00bfea825826be0bc8336fc369860"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.2"

[[deps.CommonSolve]]
git-tree-sha1 = "0eee5eb66b1cf62cd6ad1b460238e60e4b09400c"
uuid = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
version = "0.2.4"

[[deps.CommonWorldInvalidations]]
git-tree-sha1 = "ae52d1c52048455e85a387fbee9be553ec2b68d0"
uuid = "f70d9fcc-98c5-4d4a-abd7-e4cdeebd8ca8"
version = "1.0.0"

[[deps.Compat]]
deps = ["TOML", "UUIDs"]
git-tree-sha1 = "9d8a54ce4b17aa5bdce0ea5c34bc5e7c340d16ad"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "4.18.1"
weakdeps = ["Dates", "LinearAlgebra"]

    [deps.Compat.extensions]
    CompatLinearAlgebraExt = "LinearAlgebra"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "1.3.0+1"

[[deps.CompositeTypes]]
git-tree-sha1 = "bce26c3dab336582805503bed209faab1c279768"
uuid = "b152e2b5-7a66-4b01-a709-34e65c35f657"
version = "0.1.4"

[[deps.CompositionsBase]]
git-tree-sha1 = "802bb88cd69dfd1509f6670416bd4434015693ad"
uuid = "a33af91c-f02d-484b-be07-31d278c5ca2b"
version = "0.1.2"
weakdeps = ["InverseFunctions"]

    [deps.CompositionsBase.extensions]
    CompositionsBaseInverseFunctionsExt = "InverseFunctions"

[[deps.ConstructionBase]]
git-tree-sha1 = "b4b092499347b18a015186eae3042f72267106cb"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.6.0"
weakdeps = ["IntervalSets", "LinearAlgebra", "StaticArrays"]

    [deps.ConstructionBase.extensions]
    ConstructionBaseIntervalSetsExt = "IntervalSets"
    ConstructionBaseLinearAlgebraExt = "LinearAlgebra"
    ConstructionBaseStaticArraysExt = "StaticArrays"

[[deps.DataAPI]]
git-tree-sha1 = "abe83f3a2f1b857aac70ef8b269080af17764bbe"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.16.0"

[[deps.DataStructures]]
deps = ["OrderedCollections"]
git-tree-sha1 = "6c72198e6a101cccdd4c9731d3985e904ba26037"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.19.1"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
git-tree-sha1 = "9e2f36d3c96a820c678f2f1f1782582fcf685bae"
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"
version = "1.9.1"

[[deps.DiffRules]]
deps = ["IrrationalConstants", "LogExpFunctions", "NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "23163d55f885173722d1e4cf0f6110cdbaf7e272"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.15.1"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"
version = "1.11.0"

[[deps.Distributions]]
deps = ["AliasTables", "FillArrays", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SpecialFunctions", "Statistics", "StatsAPI", "StatsBase", "StatsFuns"]
git-tree-sha1 = "3bc002af51045ca3b47d2e1787d6ce02e68b943a"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.25.122"

    [deps.Distributions.extensions]
    DistributionsChainRulesCoreExt = "ChainRulesCore"
    DistributionsDensityInterfaceExt = "DensityInterface"
    DistributionsTestExt = "Test"

    [deps.Distributions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
    Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.DocStringExtensions]]
git-tree-sha1 = "7442a5dfe1ebb773c29cc2962a8980f47221d76c"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.9.5"

[[deps.DomainSets]]
deps = ["CompositeTypes", "IntervalSets", "LinearAlgebra", "StaticArrays"]
git-tree-sha1 = "c249d86e97a7e8398ce2068dce4c078a1c3464de"
uuid = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
version = "0.7.16"

    [deps.DomainSets.extensions]
    DomainSetsMakieExt = "Makie"
    DomainSetsRandomExt = "Random"

    [deps.DomainSets.weakdeps]
    Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
    Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.Downloads]]
deps = ["ArgTools", "FileWatching", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
version = "1.6.0"

[[deps.DynamicPolynomials]]
deps = ["Future", "LinearAlgebra", "MultivariatePolynomials", "MutableArithmetics", "Reexport", "Test"]
git-tree-sha1 = "3f50fa86c968fc1a9e006c07b6bc40ccbb1b704d"
uuid = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
version = "0.6.4"

[[deps.EnumX]]
git-tree-sha1 = "bddad79635af6aec424f53ed8aad5d7555dc6f00"
uuid = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
version = "1.0.5"

[[deps.ExprTools]]
git-tree-sha1 = "27415f162e6028e81c72b82ef756bf321213b6ec"
uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
version = "0.1.10"

[[deps.ExproniconLite]]
git-tree-sha1 = "c13f0b150373771b0fdc1713c97860f8df12e6c2"
uuid = "55351af7-c7e9-48d6-89ff-24e801d99491"
version = "0.10.14"

[[deps.FFTW]]
deps = ["AbstractFFTs", "FFTW_jll", "Libdl", "LinearAlgebra", "MKL_jll", "Preferences", "Reexport"]
git-tree-sha1 = "97f08406df914023af55ade2f843c39e99c5d969"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "1.10.0"

[[deps.FFTW_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "6d6219a004b8cf1e0b4dbe27a2860b8e04eba0be"
uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a"
version = "3.3.11+0"

[[deps.FLINT_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "OpenBLAS32_jll"]
git-tree-sha1 = "65248c4cbdd4392072d39dff23b385bac47e7b12"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "301.300.102+0"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
version = "1.11.0"

[[deps.FillArrays]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "173e4d8f14230a7523ae11b9a3fa9edb3e0efd78"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "1.14.0"
weakdeps = ["PDMats", "SparseArrays", "Statistics"]

    [deps.FillArrays.extensions]
    FillArraysPDMatsExt = "PDMats"
    FillArraysSparseArraysExt = "SparseArrays"
    FillArraysStatisticsExt = "Statistics"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "05882d6995ae5c12bb5f36dd2ed3f61c98cbb172"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.5"

[[deps.Format]]
git-tree-sha1 = "9c68794ef81b08086aeb32eeaf33531668d5f5fc"
uuid = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
version = "1.3.7"

[[deps.FunctionWrappers]]
git-tree-sha1 = "d62485945ce5ae9c0c48f124a84998d755bae00e"
uuid = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
version = "1.1.3"

[[deps.FunctionWrappersWrappers]]
deps = ["FunctionWrappers"]
git-tree-sha1 = "b104d487b34566608f8b4e1c39fb0b10aa279ff8"
uuid = "77dc65aa-8811-40c2-897b-53d922fa7daf"
version = "0.1.3"

[[deps.Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"
version = "1.11.0"

[[deps.GMP_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version = "6.3.0+2"

[[deps.GPUArraysCore]]
deps = ["Adapt"]
git-tree-sha1 = "83cf05ab16a73219e5f6bd1bdfa9848fa24ac627"
uuid = "46192b85-c4d5-4398-a991-12ede77f4527"
version = "0.2.0"

[[deps.Ghostscript_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Zlib_jll"]
git-tree-sha1 = "38044a04637976140074d0b0621c1edf0eb531fd"
uuid = "61579ee1-b43e-5ca0-a5da-69d92c66a64b"
version = "9.55.1+0"

[[deps.Groebner]]
deps = ["AbstractAlgebra", "Atomix", "Combinatorics", "Logging", "Nemo", "PrecompileTools", "Primes", "Printf", "Random", "TimerOutputs"]
git-tree-sha1 = "b15f687fe3572da785945e8bf3480a447c3edbbe"
uuid = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
version = "0.10.0"
weakdeps = ["DynamicPolynomials"]

    [deps.Groebner.extensions]
    GroebnerDynamicPolynomialsExt = "DynamicPolynomials"

[[deps.HashArrayMappedTries]]
git-tree-sha1 = "2eaa69a7cab70a52b9687c8bf950a5a93ec895ae"
uuid = "076d061b-32b6-4027-95e0-9a2c6f6d7e74"
version = "0.2.0"

[[deps.HypergeometricFunctions]]
deps = ["LinearAlgebra", "OpenLibm_jll", "SpecialFunctions"]
git-tree-sha1 = "68c173f4f449de5b438ee67ed0c9c748dc31a2ec"
uuid = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
version = "0.3.28"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "179267cfa5e712760cd43dcae385d7ea90cc25a4"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.5"

[[deps.HypertextLiteral]]
deps = ["Tricks"]
git-tree-sha1 = "7134810b1afce04bbc1045ca1985fbe81ce17653"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.5"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "b6d6bfdd7ce25b0f9b2f6b3dd56b2673a66c8770"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.5"

[[deps.IntegerMathUtils]]
git-tree-sha1 = "4c1acff2dc6b6967e7e750633c50bc3b8d83e617"
uuid = "18e54dd8-cb9d-406c-a71d-865a43cbb235"
version = "0.1.3"

[[deps.IntelOpenMP_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl"]
git-tree-sha1 = "ec1debd61c300961f98064cfb21287613ad7f303"
uuid = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0"
version = "2025.2.0+0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

[[deps.IntervalSets]]
git-tree-sha1 = "5fbb102dcb8b1a858111ae81d56682376130517d"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.7.11"
weakdeps = ["Random", "RecipesBase", "Statistics"]

    [deps.IntervalSets.extensions]
    IntervalSetsRandomExt = "Random"
    IntervalSetsRecipesBaseExt = "RecipesBase"
    IntervalSetsStatisticsExt = "Statistics"

[[deps.InverseFunctions]]
git-tree-sha1 = "a779299d77cd080bf77b97535acecd73e1c5e5cb"
uuid = "3587e190-3f89-42d0-90ee-14403ec27112"
version = "0.1.17"
weakdeps = ["Dates", "Test"]

    [deps.InverseFunctions.extensions]
    InverseFunctionsDatesExt = "Dates"
    InverseFunctionsTestExt = "Test"

[[deps.IrrationalConstants]]
git-tree-sha1 = "b2d91fe939cae05960e760110b328288867b5758"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.2.6"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[deps.JLLWrappers]]
deps = ["Artifacts", "Preferences"]
git-tree-sha1 = "0533e564aae234aff59ab625543145446d8b6ec2"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.7.1"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "31e996f0a15c7b280ba9f76636b3ff9e2ae58c9a"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.4"

[[deps.Jieko]]
deps = ["ExproniconLite"]
git-tree-sha1 = "2f05ed29618da60c06a87e9c033982d4f71d0b6c"
uuid = "ae98c720-c025-4a4a-838c-29b094483192"
version = "0.2.1"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "4255f0032eafd6451d707a51d5f0248b8a165e4d"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "3.1.3+0"

[[deps.JuliaSyntaxHighlighting]]
deps = ["StyledStrings"]
uuid = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
version = "1.12.0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "dda21b8cbd6a6c40d9d02a73230f9d70fed6918c"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.4.0"

[[deps.Latexify]]
deps = ["Format", "Ghostscript_jll", "InteractiveUtils", "LaTeXStrings", "MacroTools", "Markdown", "OrderedCollections", "Requires"]
git-tree-sha1 = "44f93c47f9cd6c7e431f2f2091fcba8f01cd7e8f"
uuid = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
version = "0.16.10"

    [deps.Latexify.extensions]
    DataFramesExt = "DataFrames"
    SparseArraysExt = "SparseArrays"
    SymEngineExt = "SymEngine"
    TectonicExt = "tectonic_jll"

    [deps.Latexify.weakdeps]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
    tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"

[[deps.LazyArtifacts]]
deps = ["Artifacts", "Pkg"]
uuid = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
version = "1.11.0"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.6.4"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "OpenSSL_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "8.11.1+1"

[[deps.LibGit2]]
deps = ["LibGit2_jll", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"
version = "1.11.0"

[[deps.LibGit2_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "OpenSSL_jll"]
uuid = "e37daf67-58a4-590a-8e99-b0245dd2ffc5"
version = "1.9.0+0"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "OpenSSL_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.11.3+1"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "OpenBLAS_jll", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
version = "1.12.0"

[[deps.LogExpFunctions]]
deps = ["DocStringExtensions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "13ca9e2586b89836fd20cccf56e57e2b9ae7f38f"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.29"

    [deps.LogExpFunctions.extensions]
    LogExpFunctionsChainRulesCoreExt = "ChainRulesCore"
    LogExpFunctionsChangesOfVariablesExt = "ChangesOfVariables"
    LogExpFunctionsInverseFunctionsExt = "InverseFunctions"

    [deps.LogExpFunctions.weakdeps]
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
    InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

[[deps.MIMEs]]
git-tree-sha1 = "c64d943587f7187e751162b3b84445bbbd79f691"
uuid = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
version = "1.1.0"

[[deps.MKL_jll]]
deps = ["Artifacts", "IntelOpenMP_jll", "JLLWrappers", "LazyArtifacts", "Libdl", "oneTBB_jll"]
git-tree-sha1 = "282cadc186e7b2ae0eeadbd7a4dffed4196ae2aa"
uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
version = "2025.2.0+0"

[[deps.MPFR_jll]]
deps = ["Artifacts", "GMP_jll", "Libdl"]
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version = "4.2.2+0"

[[deps.MacroTools]]
git-tree-sha1 = "1e0228a030642014fe5cfe68c2c0a818f9e3f522"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.16"

[[deps.Markdown]]
deps = ["Base64", "JuliaSyntaxHighlighting", "StyledStrings"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "ec4f7fbeab05d7747bdf98eb74d130a2a2ed298d"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.2.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
version = "1.11.0"

[[deps.Moshi]]
deps = ["ExproniconLite", "Jieko"]
git-tree-sha1 = "53f817d3e84537d84545e0ad749e483412dd6b2a"
uuid = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
version = "0.3.7"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2025.5.20"

[[deps.MultivariatePolynomials]]
deps = ["DataStructures", "LinearAlgebra", "MutableArithmetics"]
git-tree-sha1 = "d38b8653b1cdfac5a7da3b819c0a8d6024f9a18c"
uuid = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
version = "0.5.13"
weakdeps = ["ChainRulesCore"]

    [deps.MultivariatePolynomials.extensions]
    MultivariatePolynomialsChainRulesCoreExt = "ChainRulesCore"

[[deps.MutableArithmetics]]
deps = ["LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "22df8573f8e7c593ac205455ca088989d0a2c7a0"
uuid = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
version = "1.6.7"

[[deps.NaNMath]]
deps = ["OpenLibm_jll"]
git-tree-sha1 = "9b8215b1ee9e78a293f99797cd31375471b2bcae"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "1.1.3"

[[deps.Nemo]]
deps = ["AbstractAlgebra", "FLINT_jll", "LinearAlgebra", "Random", "RandomExtensions", "SHA"]
git-tree-sha1 = "e96d6ac8a79333ee14bb5822d46ae16919d2a4ce"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.52.2"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.3.0"

[[deps.OffsetArrays]]
git-tree-sha1 = "117432e406b5c023f665fa73dc26e79ec3630151"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.17.0"
weakdeps = ["Adapt"]

    [deps.OffsetArrays.extensions]
    OffsetArraysAdaptExt = "Adapt"

[[deps.OpenBLAS32_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "ece4587683695fe4c5f20e990da0ed7e83c351e7"
uuid = "656ef2d0-ae68-5445-9ca0-591084a874a2"
version = "0.3.29+0"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.29+0"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"
version = "0.8.7+0"

[[deps.OpenSSL_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "3.5.1+0"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1346c9208249809840c91b26703912dff463d335"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.6+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "05868e21324cede2207c6f0f466b4bfef6d5e7ee"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.8.1"

[[deps.PDMats]]
deps = ["LinearAlgebra", "SparseArrays", "SuiteSparse"]
git-tree-sha1 = "f07c06228a1c670ae4c87d1276b92c7c597fdda0"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.11.35"

[[deps.Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "34c0e9ad262e5f7fc75b10a9952ca7692cfc5fbe"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.3"

[[deps.Parsers]]
deps = ["Dates", "PrecompileTools", "UUIDs"]
git-tree-sha1 = "7d2f8f21da5db6a806faf7b9b292296da42b2810"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.8.3"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "Random", "SHA", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.12.0"
weakdeps = ["REPL"]

    [deps.Pkg.extensions]
    REPLExt = "REPL"

[[deps.PlotlyBase]]
deps = ["ColorSchemes", "Colors", "Dates", "DelimitedFiles", "DocStringExtensions", "JSON", "LaTeXStrings", "Logging", "Parameters", "Pkg", "REPL", "Requires", "Statistics", "UUIDs"]
git-tree-sha1 = "28278bb0053da0fd73537be94afd1682cc5a0a83"
uuid = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
version = "0.8.21"

    [deps.PlotlyBase.extensions]
    DataFramesExt = "DataFrames"
    DistributionsExt = "Distributions"
    IJuliaExt = "IJulia"
    JSON3Ext = "JSON3"

    [deps.PlotlyBase.weakdeps]
    DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
    Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
    IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
    JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[[deps.PlutoPlotly]]
deps = ["AbstractPlutoDingetjes", "Artifacts", "ColorSchemes", "Colors", "Dates", "Downloads", "HypertextLiteral", "InteractiveUtils", "LaTeXStrings", "Markdown", "Pkg", "PlotlyBase", "PrecompileTools", "Reexport", "ScopedValues", "Scratch", "TOML"]
git-tree-sha1 = "8acd04abc9a636ef57004f4c2e6f3f6ed4611099"
uuid = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
version = "0.6.5"

    [deps.PlutoPlotly.extensions]
    PlotlyKaleidoExt = "PlotlyKaleido"
    UnitfulExt = "Unitful"

    [deps.PlutoPlotly.weakdeps]
    PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
    Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "Downloads", "FixedPointNumbers", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "MIMEs", "Markdown", "Random", "Reexport", "URIs", "UUIDs"]
git-tree-sha1 = "f53232a27a8c1c836d3998ae1e17d898d4df2a46"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.72"

[[deps.PreallocationTools]]
deps = ["Adapt", "ArrayInterface", "PrecompileTools"]
git-tree-sha1 = "c05b4c6325262152483a1ecb6c69846d2e01727b"
uuid = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
version = "0.4.34"

    [deps.PreallocationTools.extensions]
    PreallocationToolsForwardDiffExt = "ForwardDiff"
    PreallocationToolsReverseDiffExt = "ReverseDiff"
    PreallocationToolsSparseConnectivityTracerExt = "SparseConnectivityTracer"

    [deps.PreallocationTools.weakdeps]
    ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
    ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
    SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "5aa36f7049a63a1528fe8f7c3f2113413ffd4e1f"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.2.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "0f27480397253da18fe2c12a4ba4eb9eb208bf3d"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.5.0"

[[deps.Primes]]
deps = ["IntegerMathUtils"]
git-tree-sha1 = "25cdd1d20cd005b52fc12cb6be3f75faaf59bb9b"
uuid = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
version = "0.5.7"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.ProgressLogging]]
deps = ["Logging", "SHA", "UUIDs"]
git-tree-sha1 = "d95ed0324b0799843ac6f7a6a85e65fe4e5173f0"
uuid = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
version = "0.1.5"

[[deps.PtrArrays]]
git-tree-sha1 = "1d36ef11a9aaf1e8b74dacc6a731dd1de8fd493d"
uuid = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"
version = "1.3.0"

[[deps.QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "9da16da70037ba9d701192e27befedefb91ec284"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.11.2"

    [deps.QuadGK.extensions]
    QuadGKEnzymeExt = "Enzyme"

    [deps.QuadGK.weakdeps]
    Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[[deps.REPL]]
deps = ["InteractiveUtils", "JuliaSyntaxHighlighting", "Markdown", "Sockets", "StyledStrings", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.RandomExtensions]]
deps = ["Random", "SparseArrays"]
git-tree-sha1 = "b8a399e95663485820000f26b6a43c794e166a49"
uuid = "fb686558-2515-59ef-acaa-46db3789a887"
version = "0.4.4"

[[deps.RecipesBase]]
deps = ["PrecompileTools"]
git-tree-sha1 = "5c3d09cc4f31f5fc6af001c250bf1278733100ff"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.3.4"

[[deps.RecursiveArrayTools]]
deps = ["Adapt", "ArrayInterface", "DocStringExtensions", "GPUArraysCore", "LinearAlgebra", "RecipesBase", "StaticArraysCore", "Statistics", "SymbolicIndexingInterface"]
git-tree-sha1 = "51bdb23afaaa551f923a0e990f7c44a4451a26f1"
uuid = "731186ca-8d62-57ce-b412-fbd966d074cd"
version = "3.39.0"

    [deps.RecursiveArrayTools.extensions]
    RecursiveArrayToolsFastBroadcastExt = "FastBroadcast"
    RecursiveArrayToolsForwardDiffExt = "ForwardDiff"
    RecursiveArrayToolsKernelAbstractionsExt = "KernelAbstractions"
    RecursiveArrayToolsMeasurementsExt = "Measurements"
    RecursiveArrayToolsMonteCarloMeasurementsExt = "MonteCarloMeasurements"
    RecursiveArrayToolsReverseDiffExt = ["ReverseDiff", "Zygote"]
    RecursiveArrayToolsSparseArraysExt = ["SparseArrays"]
    RecursiveArrayToolsStructArraysExt = "StructArrays"
    RecursiveArrayToolsTablesExt = ["Tables"]
    RecursiveArrayToolsTrackerExt = "Tracker"
    RecursiveArrayToolsZygoteExt = "Zygote"

    [deps.RecursiveArrayTools.weakdeps]
    FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
    ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
    KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
    Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
    MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
    ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
    SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
    StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
    Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
    Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
    Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "62389eeff14780bfe55195b7204c0d8738436d64"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.1"

[[deps.Rmath]]
deps = ["Random", "Rmath_jll"]
git-tree-sha1 = "5b3d50eb374cea306873b371d3f8d3915a018f0b"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.9.0"

[[deps.Rmath_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "58cdd8fb2201a6267e1db87ff148dd6c1dbd8ad8"
uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f"
version = "0.5.1+0"

[[deps.RuntimeGeneratedFunctions]]
deps = ["ExprTools", "SHA", "Serialization"]
git-tree-sha1 = "86a8a8b783481e1ea6b9c91dd949cb32191f8ab4"
uuid = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
version = "0.5.15"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.SciMLBase]]
deps = ["ADTypes", "Accessors", "Adapt", "ArrayInterface", "CommonSolve", "ConstructionBase", "Distributed", "DocStringExtensions", "EnumX", "FunctionWrappersWrappers", "IteratorInterfaceExtensions", "LinearAlgebra", "Logging", "Markdown", "Moshi", "PreallocationTools", "PrecompileTools", "Preferences", "Printf", "RecipesBase", "RecursiveArrayTools", "Reexport", "RuntimeGeneratedFunctions", "SciMLOperators", "SciMLPublic", "SciMLStructures", "StaticArraysCore", "Statistics", "SymbolicIndexingInterface"]
git-tree-sha1 = "7680fbbc8a4fdf9837b4cae5e3fbebe53ec8e4ff"
uuid = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
version = "2.122.0"

    [deps.SciMLBase.extensions]
    SciMLBaseChainRulesCoreExt = "ChainRulesCore"
    SciMLBaseDistributionsExt = "Distributions"
    SciMLBaseEnzymeExt = "Enzyme"
    SciMLBaseForwardDiffExt = "ForwardDiff"
    SciMLBaseMLStyleExt = "MLStyle"
    SciMLBaseMakieExt = "Makie"
    SciMLBaseMeasurementsExt = "Measurements"
    SciMLBaseMonteCarloMeasurementsExt = "MonteCarloMeasurements"
    SciMLBaseMooncakeExt = "Mooncake"
    SciMLBasePartialFunctionsExt = "PartialFunctions"
    SciMLBasePyCallExt = "PyCall"
    SciMLBasePythonCallExt = "PythonCall"
    SciMLBaseRCallExt = "RCall"
    SciMLBaseReverseDiffExt = "ReverseDiff"
    SciMLBaseTrackerExt = "Tracker"
    SciMLBaseZygoteExt = ["Zygote", "ChainRulesCore"]

    [deps.SciMLBase.weakdeps]
    ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
    ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
    Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
    Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
    ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
    MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
    Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
    Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
    MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
    Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
    PartialFunctions = "570af359-4316-4cb7-8c74-252c00c2016b"
    PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
    PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
    RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
    ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
    Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
    Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[[deps.SciMLOperators]]
deps = ["Accessors", "ArrayInterface", "DocStringExtensions", "LinearAlgebra", "MacroTools"]
git-tree-sha1 = "c1053ba68ede9e4005fc925dd4e8723fcd96eef8"
uuid = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
version = "1.9.0"
weakdeps = ["SparseArrays", "StaticArraysCore"]

    [deps.SciMLOperators.extensions]
    SciMLOperatorsSparseArraysExt = "SparseArrays"
    SciMLOperatorsStaticArraysCoreExt = "StaticArraysCore"

[[deps.SciMLPublic]]
git-tree-sha1 = "ed647f161e8b3f2973f24979ec074e8d084f1bee"
uuid = "431bcebd-1456-4ced-9d72-93c2757fff0b"
version = "1.0.0"

[[deps.SciMLStructures]]
deps = ["ArrayInterface"]
git-tree-sha1 = "566c4ed301ccb2a44cbd5a27da5f885e0ed1d5df"
uuid = "53ae85a6-f571-4167-b2af-e1d143709226"
version = "1.7.0"

[[deps.ScopedValues]]
deps = ["HashArrayMappedTries", "Logging"]
git-tree-sha1 = "c3b2323466378a2ba15bea4b2f73b081e022f473"
uuid = "7e506255-f358-4e82-b7e4-beb19740aa63"
version = "1.5.0"

[[deps.Scratch]]
deps = ["Dates"]
git-tree-sha1 = "9b81b8393e50b7d4e6d0a9f14e192294d3b7c109"
uuid = "6c6a2e73-6563-6170-7368-637461726353"
version = "1.3.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
version = "1.11.0"

[[deps.Setfield]]
deps = ["ConstructionBase", "Future", "MacroTools", "StaticArraysCore"]
git-tree-sha1 = "c5391c6ace3bc430ca630251d02ea9687169ca68"
uuid = "efcf1570-3423-57d1-acb7-fd33fddbac46"
version = "1.1.2"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
version = "1.11.0"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "64d974c2e6fdf07f8155b5b2ca2ffa9069b608d9"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.2.2"

[[deps.SparseArrays]]
deps = ["Libdl", "LinearAlgebra", "Random", "Serialization", "SuiteSparse_jll"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
version = "1.12.0"

[[deps.SpecialFunctions]]
deps = ["IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "f2685b435df2613e25fc10ad8c26dddb8640f547"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "2.6.1"
weakdeps = ["ChainRulesCore"]

    [deps.SpecialFunctions.extensions]
    SpecialFunctionsChainRulesCoreExt = "ChainRulesCore"

[[deps.StaticArrays]]
deps = ["LinearAlgebra", "PrecompileTools", "Random", "StaticArraysCore"]
git-tree-sha1 = "b8693004b385c842357406e3af647701fe783f98"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "1.9.15"
weakdeps = ["ChainRulesCore", "Statistics"]

    [deps.StaticArrays.extensions]
    StaticArraysChainRulesCoreExt = "ChainRulesCore"
    StaticArraysStatisticsExt = "Statistics"

[[deps.StaticArraysCore]]
git-tree-sha1 = "6ab403037779dae8c514bad259f32a447262455a"
uuid = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
version = "1.4.4"

[[deps.Statistics]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "ae3bb1eb3bba077cd276bc5cfc337cc65c3075c0"
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
version = "1.11.1"
weakdeps = ["SparseArrays"]

    [deps.Statistics.extensions]
    SparseArraysExt = ["SparseArrays"]

[[deps.StatsAPI]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "9d72a13a3f4dd3795a195ac5a44d7d6ff5f552ff"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.7.1"

[[deps.StatsBase]]
deps = ["AliasTables", "DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "a136f98cefaf3e2924a66bd75173d1c891ab7453"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.34.7"

[[deps.StatsFuns]]
deps = ["HypergeometricFunctions", "IrrationalConstants", "LogExpFunctions", "Reexport", "Rmath", "SpecialFunctions"]
git-tree-sha1 = "91f091a8716a6bb38417a6e6f274602a19aaa685"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "1.5.2"
weakdeps = ["ChainRulesCore", "InverseFunctions"]

    [deps.StatsFuns.extensions]
    StatsFunsChainRulesCoreExt = "ChainRulesCore"
    StatsFunsInverseFunctionsExt = "InverseFunctions"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.11.0"

[[deps.SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "Serialization", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[deps.SuiteSparse_jll]]
deps = ["Artifacts", "Libdl", "libblastrampoline_jll"]
uuid = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
version = "7.8.3+2"

[[deps.SymbolicIndexingInterface]]
deps = ["Accessors", "ArrayInterface", "RuntimeGeneratedFunctions", "StaticArraysCore"]
git-tree-sha1 = "94c58884e013efff548002e8dc2fdd1cb74dfce5"
uuid = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
version = "0.3.46"

    [deps.SymbolicIndexingInterface.extensions]
    SymbolicIndexingInterfacePrettyTablesExt = "PrettyTables"

    [deps.SymbolicIndexingInterface.weakdeps]
    PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[[deps.SymbolicLimits]]
deps = ["SymbolicUtils"]
git-tree-sha1 = "f75c7deb7e11eea72d2c1ea31b24070b713ba061"
uuid = "19f23fe9-fdab-4a78-91af-e7b7767979c3"
version = "0.2.3"

[[deps.SymbolicUtils]]
deps = ["AbstractTrees", "ArrayInterface", "Bijections", "ChainRulesCore", "Combinatorics", "ConstructionBase", "DataStructures", "DocStringExtensions", "DynamicPolynomials", "ExproniconLite", "LinearAlgebra", "MultivariatePolynomials", "NaNMath", "Setfield", "SparseArrays", "SpecialFunctions", "StaticArrays", "SymbolicIndexingInterface", "TaskLocalValues", "TermInterface", "TimerOutputs", "Unityper"]
git-tree-sha1 = "a85b4262a55dbd1af39bb6facf621d79ca6a322d"
uuid = "d1185830-fcd6-423d-90d6-eec64667417b"
version = "3.32.0"

    [deps.SymbolicUtils.extensions]
    SymbolicUtilsLabelledArraysExt = "LabelledArrays"
    SymbolicUtilsReverseDiffExt = "ReverseDiff"

    [deps.SymbolicUtils.weakdeps]
    LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
    ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[[deps.Symbolics]]
deps = ["ADTypes", "ArrayInterface", "Bijections", "CommonWorldInvalidations", "ConstructionBase", "DataStructures", "DiffRules", "Distributions", "DocStringExtensions", "DomainSets", "DynamicPolynomials", "LaTeXStrings", "Latexify", "Libdl", "LinearAlgebra", "LogExpFunctions", "MacroTools", "Markdown", "NaNMath", "OffsetArrays", "PrecompileTools", "Primes", "RecipesBase", "Reexport", "RuntimeGeneratedFunctions", "SciMLBase", "SciMLPublic", "Setfield", "SparseArrays", "SpecialFunctions", "StaticArraysCore", "SymbolicIndexingInterface", "SymbolicLimits", "SymbolicUtils", "TermInterface"]
git-tree-sha1 = "1b09f5faec5284f505c40e68ba565115e7d48718"
uuid = "0c5d862f-8b57-4792-8d23-62f2024744c7"
version = "6.56.0"

    [deps.Symbolics.extensions]
    SymbolicsD3TreesExt = "D3Trees"
    SymbolicsForwardDiffExt = "ForwardDiff"
    SymbolicsGroebnerExt = "Groebner"
    SymbolicsLuxExt = "Lux"
    SymbolicsNemoExt = "Nemo"
    SymbolicsPreallocationToolsExt = ["PreallocationTools", "ForwardDiff"]
    SymbolicsSymPyExt = "SymPy"
    SymbolicsSymPyPythonCallExt = "SymPyPythonCall"

    [deps.Symbolics.weakdeps]
    D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
    ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
    Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
    Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
    Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
    PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
    SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
    SymPyPythonCall = "bc8888f7-b21e-4b7c-a06a-5d9c9496438c"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.10.0"

[[deps.TaskLocalValues]]
git-tree-sha1 = "67e469338d9ce74fc578f7db1736a74d93a49eb8"
uuid = "ed4db957-447d-4319-bfb6-7fa9ae7ecf34"
version = "0.1.3"

[[deps.TensorCore]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "1feb45f88d133a655e001435632f019a9a1bcdb6"
uuid = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"
version = "0.1.1"

[[deps.TermInterface]]
git-tree-sha1 = "d673e0aca9e46a2f63720201f55cc7b3e7169b16"
uuid = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
version = "2.0.0"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
version = "1.11.0"

[[deps.TimerOutputs]]
deps = ["ExprTools", "Printf"]
git-tree-sha1 = "3748bd928e68c7c346b52125cf41fff0de6937d0"
uuid = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
version = "0.5.29"

    [deps.TimerOutputs.extensions]
    FlameGraphsExt = "FlameGraphs"

    [deps.TimerOutputs.weakdeps]
    FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"

[[deps.Tricks]]
git-tree-sha1 = "372b90fe551c019541fafc6ff034199dc19c8436"
uuid = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
version = "0.1.12"

[[deps.URIs]]
git-tree-sha1 = "bef26fb046d031353ef97a82e3fdb6afe7f21b1a"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.6.1"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"

[[deps.UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

[[deps.Unityper]]
deps = ["ConstructionBase"]
git-tree-sha1 = "25008b734a03736c41e2a7dc314ecb95bd6bbdb0"
uuid = "a7c27f48-0311-42f6-a7f8-2c11e75eb415"
version = "0.1.6"

[[deps.UnsafeAtomics]]
git-tree-sha1 = "b13c4edda90890e5b04ba24e20a310fbe6f249ff"
uuid = "013be700-e6cd-48c3-b4a1-df204f14c38f"
version = "0.3.0"

    [deps.UnsafeAtomics.extensions]
    UnsafeAtomicsLLVM = ["LLVM"]

    [deps.UnsafeAtomics.weakdeps]
    LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.3.1+2"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"
version = "5.15.0+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.64.0+1"

[[deps.oneTBB_jll]]
deps = ["Artifacts", "JLLWrappers", "LazyArtifacts", "Libdl"]
git-tree-sha1 = "1350188a69a6e46f799d3945beef36435ed7262f"
uuid = "1317d2d5-d96f-522e-a858-c73665f53c3e"
version = "2022.0.0+1"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "17.5.0+2"
"""

# ╔═╡ Cell order:
# ╠═6188ff3e-cfd5-4c9c-aa39-619dc280d494
# ╟─1bbedd43-9e69-4ba0-a251-855f1f63dcf8
# ╟─4e31b3c7-e7ab-4a10-ba04-292dd03a3732
# ╠═5d8719c8-4b50-435b-9c3e-aa8eee50df98
# ╠═78d77dbb-1f2c-4b7c-a1ce-fa775ac7bd5c
# ╠═d24ceb91-f463-497f-a914-5c6e90e766ee
# ╠═d1f5e223-cc49-4fe8-9b2e-c1ccecf2315a
# ╠═614a3832-7bc7-4bd3-a09d-50b76afdd7cf
# ╠═dea0645d-cb7c-4488-913b-ba225595aceb
# ╠═579cfd9f-e872-4ec5-b913-c90f8e183247
# ╠═a1e5796b-6f2f-44c6-b5bf-df6c9ee20960
# ╠═55e64939-9298-4a15-a2b0-0d13c23d03dc
# ╠═1d49ebac-04a4-44a5-890c-f565d34246c1
# ╠═12104212-be60-42e8-85ba-518555ca31f2
# ╠═ccec9a65-e249-4d28-bacb-6b53f8bfabf4
# ╠═9f5c360c-7699-4c78-8e4b-8a2d316bc304
# ╠═d060f642-89bf-430d-a509-25133ab0aacd
# ╠═cc9dbdc7-56a7-410e-9787-6ce75748596e
# ╠═96556fec-4bea-4132-946a-92d17372df54
# ╠═4ff2ef66-06eb-4df0-b491-10ab7a81d65d
# ╠═b3d2ba8e-7a02-4af1-9e4a-d9ab1b4676df
# ╟─a7b582ba-57fa-4f90-b017-5a9d059c30e5
# ╟─7a3bd5df-0f9f-489c-b522-4098c325c0c0
# ╠═29020170-3173-40a4-aac6-9d0fd1212aaf
# ╠═add5414e-8a87-4164-9c2c-a3deeb13a864
# ╠═210c693b-e0a2-4660-9389-bdc3e410080a
# ╠═05ec38ea-3431-490c-bc38-24f8c1b2d54f
# ╠═3f8684cb-03c7-4c86-86b5-0af2d9a32418
# ╟─e2fea7d5-00a3-4796-ad51-26f2dcffa55b
# ╠═5ea371a8-8035-4ba3-ab83-a9ffa2e3d504
# ╠═d430c8ec-fa65-4e72-951e-987ba9f2f160
# ╠═f047c190-0bf3-4763-9f31-b4272e837dd2
# ╟─360de109-d7db-4402-bca8-5b39c6f17da9
# ╠═f25f798f-0ecc-4931-b8b5-9c958b83850f
# ╠═d60d4d65-8896-40ee-b52f-17d66999c727
# ╠═e6bbca73-e59c-4b6a-854e-438222778110
# ╠═687b7062-ee25-4498-948f-43b187e0ccfa
# ╠═8902f19a-6b93-458a-9198-f2322b2f5ab5
# ╠═7ca06983-11c1-4203-9bd0-0cc1a461b74f
# ╠═c9bf8e13-eee2-45ae-9ce5-4901c344c8f6
# ╠═43c34152-fc5f-4497-882f-7f42bd4e6b99
# ╠═da2a2e26-f217-41e0-8485-6517af621d2a
# ╠═3dfbfc66-8f87-4906-84f5-495bf113e4ef
# ╠═0de7835c-eb50-4de0-874b-e08270d988aa
# ╠═8ef12535-49a1-46fe-a26c-880358755a16
# ╠═c077d6f7-9fc7-4c0b-bf42-26882a374cbf
# ╠═68e54426-2a9f-409c-acd9-e0e6e9681487
# ╠═4c8103ff-8928-4c78-ad63-d0175738ef7f
# ╠═e2438fc6-78e9-4d06-9e4c-ee4ff22d0062
# ╠═0ee489a5-3769-4bdf-9e88-cdf54199d692
# ╠═75fc91ce-840f-4625-87eb-1870f668f5c0
# ╠═03a80695-170a-4a2f-a124-630dc3dbf5b6
# ╠═99ee6828-0a0d-4048-8ffd-d25b7848368b
# ╠═8fe6d5f7-7ec9-4a67-a557-ffe51124066b
# ╠═277a6190-3f6e-4008-aa2c-aac84d205f42
# ╠═1d58e672-5c50-4000-8842-7c592b22c32e
# ╠═65c2f4a8-92f7-4673-ba7a-ba2367b558aa
# ╠═ae0e4d63-8348-46ac-994f-11b1ce1001fb
# ╠═7b55d65d-7654-4ac5-9b3c-d0f8b52905cd
# ╠═0e3d2a52-e357-4b54-80ce-fb7f44c6334f
# ╠═060c9127-775a-45c0-b31b-2a6dcacac179
# ╠═0f034701-7953-4428-bde9-b2a21fbc5c6e
# ╠═52149e10-3a89-412a-bd43-e29e26592551
# ╠═94fc6b36-7e38-4fc1-af47-9c82d6595e6b
# ╠═cca1bbd7-5455-47f9-bef9-448ece10c2b6
# ╠═d94908f6-1d0f-46ff-8c8e-ef0d407b539d
# ╠═a015f013-7333-44e7-b7bb-a293aefeac0b
# ╠═3aaca98b-4b75-4970-97cf-b4649f443017
# ╠═93d2f1ad-06ed-4080-a0ce-5ec1eb642e4e
# ╠═02237fbb-f2d3-4436-ad0e-c60df62befaa
# ╠═239a50ff-3970-47ff-b772-fc3e0cb247fe
# ╠═fa4b8951-569e-4517-9b0a-f77a22a31fca
# ╟─f0a4c439-ee9b-4001-97db-66f6ac5afd5a
# ╠═0e8564a1-d300-4ca1-84f3-93ebea6ad08a
# ╠═e1908cc5-a4c1-4802-9f23-d9905a68cc36
# ╠═281a5cac-4e00-42d6-b331-ea5d80888f27
# ╠═089b0602-077a-4074-a424-0a6afab8bcf4
# ╠═00a3df8b-9642-461a-8d37-9342c121240e
# ╠═a88a10fe-2a02-458d-898a-25cdb0d15af4
# ╠═f73569cb-ef42-432a-8910-cbb0176cea18
# ╠═37e33e90-0d44-4a9d-abeb-a7ee1cf9f977
# ╠═84209251-8b66-4d63-ba8f-1b7c1a12b382
# ╠═951a5946-ab54-4aff-be89-b8d5ea90fa1a
# ╠═9a9a1d8e-df81-4aa2-b0f3-49cb90f8a398
# ╠═c246fdfc-321c-4856-8a4b-cf6cb4ba1594
# ╠═395d3a63-b7b8-44b5-97ab-740c4849db26
# ╠═d297ea1c-e0ad-4fe7-bbc2-fc7d6269f8ba
# ╟─72aca1bf-3997-4be3-b316-921b45480c1a
# ╠═12f7733a-edd6-481f-8166-ef967520b35a
# ╠═3693ffe9-979b-416a-85de-8438f00a6fc2
# ╠═765b90b8-060d-4b68-8201-309abe4adebc
# ╠═47c0c813-08a2-4173-9853-f12874449b6e
# ╠═70ff038f-e684-4fde-8c93-0358b0181c01
# ╠═53a45db3-8571-4fc7-a855-5173030b7cb9
# ╠═6923e13d-a4c5-45c9-a1b2-f0104932d709
# ╠═77032c75-0cae-48a0-a5f0-7ca4de2ff3ea
# ╟─4b283a44-214a-4bc0-8eb9-031a0e124a82
# ╠═e91921c5-4600-4344-85c7-e35820ba2daa
# ╠═423c7abb-f274-4010-bd08-95adc5890204
# ╟─c695e4d3-c49d-4587-8adc-cdd4c001325e
# ╠═897afffa-77e8-11ef-1a54-c73d1df8f6a4
# ╠═aa38e7f6-b8d2-4270-9142-1aa688041eb4
# ╠═4621f804-6a44-4c46-af37-3d364ba74cfe
# ╠═fbd2b939-c816-42dd-a65e-94abce3dc91a
# ╠═9b488729-aadc-4c1d-b971-6931d4bc9a08
# ╠═af2ca94f-f684-4df7-90de-f1e699004e0f
# ╟─e7c1cbf4-7939-45a2-a754-b36ae9bdcab4
# ╟─9d10ab94-38d5-406e-8697-7f5bc0c11df2
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
